// Bookkeeping resources: software pages and how-to guides. General information, not tax or legal advice.
// Facts that change (fees, thresholds, due dates) are phrased with "check the current ..." on purpose. Review once a year.
// MCC Solutions does not claim any software certification here. Add credentials only once they are real.

const SOFTWARE = [
  {
    slug: "quickbooks-online", name: "QuickBooks Online", short: "QuickBooks",
    title: "QuickBooks Online Bookkeeping Help in NJ",
    description: "Monthly bookkeeping, cleanup and reconciliation in QuickBooks Online for New Jersey small businesses. Your account stays in your name.",
    intro: "QuickBooks Online is the accounting program most small businesses and most accountants already use. We keep books inside your own QuickBooks Online account, so your accountant, lender and you all see the same numbers.",
    fits: ["Most service businesses, contractors, retail shops and restaurants", "Businesses whose CPA already works in QuickBooks", "Owners who want bank feeds, invoicing and payroll connected"],
    work: ["Connecting and monitoring bank and credit card feeds", "Categorizing transactions and cleaning up duplicates and uncategorized items", "Monthly bank and card reconciliation", "Setting up a clean chart of accounts, classes or locations if you need them", "Invoices, bills, sales tax settings and 1099 vendor tracking", "Monthly profit and loss, balance sheet and a short note on what changed"],
    watch: ["Make sure you are the account owner and your bookkeeper is invited as a user. Never share one login.", "Plan levels change what you can do (users, classes, budgets). Check Intuit's current plan comparison before you buy.", "Bank feeds sometimes drop. A feed that stopped three months ago is the most common reason books are behind."],
    faqs: [["Do you use my QuickBooks account or yours?", "Yours. You own the subscription and the data. We are added as a user and can be removed any time."], ["Can you fix a QuickBooks file that is a mess?", "Usually yes. We review it first and give a written quote for cleanup before changing anything. See the guide on catching up behind books."], ["Are you affiliated with Intuit?", "No. MCC Solutions is an independent firm. QuickBooks is a trademark of Intuit Inc."]],
    guides: ["what-is-a-quickbooks-proadvisor", "how-to-reconcile-a-bank-account", "how-to-catch-up-on-behind-books"],
  },
  {
    slug: "xero", name: "Xero", short: "Xero",
    title: "Xero Bookkeeping Help in NJ",
    description: "Bookkeeping and reconciliation in Xero for New Jersey small businesses, including cleanup and moving from spreadsheets or another program.",
    intro: "Xero is a cloud accounting program with strong bank reconciliation and unlimited users on its plans. If your business already runs on Xero, we work in it. If you are choosing, we will tell you plainly whether it fits.",
    fits: ["Businesses that want several people to have access without per-user fees", "Owners who like a simple, visual reconciliation screen", "Companies working with international customers or currencies"],
    work: ["Bank feed setup and monthly reconciliation", "Coding bank statement lines and clearing the reconcile queue", "Invoices, bills and repeating invoices", "Chart of accounts review and tracking categories", "Month-end reports and a short summary"],
    watch: ["Some US accountants are less familiar with Xero than QuickBooks. Ask your CPA before you switch.", "Payroll in Xero for the US runs through partner integrations. Confirm how it will work for New Jersey before committing.", "Check Xero's current plan limits, for example the number of bills and bank transactions on entry plans."],
    faqs: [["Can you move us from QuickBooks to Xero or back?", "Yes, as a quoted project. Start with the guide on switching accounting software to see what moves cleanly and what does not."], ["Do you support Xero payroll for NJ?", "We can help set up and process payroll through the payroll tool that fits your business. Ask us about your situation."], ["Are you affiliated with Xero?", "No. MCC Solutions is an independent firm. Xero is a trademark of Xero Limited."]],
    guides: ["how-to-switch-accounting-software", "how-to-reconcile-a-bank-account", "chart-of-accounts-for-small-business"],
  },
  {
    slug: "wave", name: "Wave", short: "Wave",
    title: "Wave Accounting Bookkeeping Help in NJ",
    description: "Bookkeeping help for Wave users in New Jersey, and when it makes sense to outgrow Wave. Cleanup, reconciliation and moves to another platform.",
    intro: "Wave is a popular starting point for freelancers and very small businesses. Many owners keep it for years. Others outgrow it when they add employees, inventory or an outside accountant.",
    fits: ["Freelancers, consultants and sole proprietors with simple books", "New businesses that want to start without a monthly software cost", "Owners who mostly need invoicing and basic reports"],
    work: ["Categorizing transactions and reconciling accounts", "Cleaning up uncategorized and duplicate entries", "Year-end reports your tax preparer can use", "Planning and doing a move to QuickBooks Online or Xero when it is time"],
    watch: ["Features and pricing at Wave have changed over the years. Check Wave's current offering for payroll and payments before you rely on it.", "Wave has fewer integrations and reports than the larger programs. A growing business may feel that.", "Confirm your tax preparer is comfortable with Wave exports."],
    faqs: [["Is Wave good enough for my business?", "For simple books, often yes. If you have employees, inventory, multiple entities or a CPA who wants a different program, we can talk through a move."], ["Can you take my Wave data to QuickBooks?", "Yes, as a quoted project. See the guide on switching accounting software."], ["Are you affiliated with Wave?", "No. MCC Solutions is an independent firm."]],
    guides: ["how-to-switch-accounting-software", "separating-personal-and-business-finances", "how-to-set-up-bookkeeping-for-a-new-nj-llc"],
  },
  {
    slug: "freshbooks", name: "FreshBooks", short: "FreshBooks",
    title: "FreshBooks Bookkeeping Help in NJ",
    description: "Bookkeeping, invoice clean-up and reconciliation in FreshBooks for New Jersey freelancers and service businesses.",
    intro: "FreshBooks is built around invoicing, time tracking and getting paid, which suits freelancers, agencies and professional services. We keep the books behind the invoices accurate and reconciled.",
    fits: ["Consultants, designers, agencies and other service firms", "Businesses that bill by the hour or by project", "Owners who send many invoices and want clear aging reports"],
    work: ["Reconciling bank and card accounts to FreshBooks", "Matching client payments to invoices and clearing old open invoices", "Expense categorization and receipt matching", "Monthly reports and a year-end package for your tax preparer"],
    watch: ["Check how many billable clients each plan includes before you sign up. Plans have used client limits.", "Heavier accounting features like inventory are limited compared to larger platforms.", "Make sure your tax preparer accepts FreshBooks reports."],
    faqs: [["Do you chase unpaid invoices?", "We report on them each month so you can follow up. Collections are your call."], ["Can you move us to QuickBooks later?", "Yes, as a quoted project."], ["Are you affiliated with FreshBooks?", "No. MCC Solutions is an independent firm."]],
    guides: ["how-to-reconcile-a-bank-account", "what-to-send-your-bookkeeper-each-month", "how-to-switch-accounting-software"],
  },
  {
    slug: "zoho-books", name: "Zoho Books", short: "Zoho Books",
    title: "Zoho Books Bookkeeping Help in NJ",
    description: "Bookkeeping and reconciliation in Zoho Books for New Jersey businesses, especially those already using other Zoho apps.",
    intro: "Zoho Books makes the most sense when the rest of the business already runs on Zoho (CRM, inventory, billing). We keep the books connected and reconciled so the reports can be trusted.",
    fits: ["Businesses already using other Zoho apps", "Companies that want inventory and sales orders with their accounting", "Owners who want solid features at a modest software cost"],
    work: ["Bank feed setup and reconciliation", "Cleaning up the chart of accounts and item records", "Bills, invoices and sales tax settings", "Monthly financial reports"],
    watch: ["Check how well your bank and payment processors connect before choosing it.", "Fewer US accountants know Zoho Books than QuickBooks. Confirm yours does.", "Check the current plan limits for users and automations."],
    faqs: [["Is Zoho Books right for a tiny business?", "It can be, especially with other Zoho apps. For a business that only needs books, QuickBooks Online or Xero may be easier to find help for."], ["Do you set up integrations?", "We handle the accounting side. Ask us what you need connected."], ["Are you affiliated with Zoho?", "No. MCC Solutions is an independent firm."]],
    guides: ["chart-of-accounts-for-small-business", "how-to-reconcile-a-bank-account", "how-to-switch-accounting-software"],
  },
  {
    slug: "gusto-payroll", name: "Gusto and payroll software", short: "Payroll",
    title: "Payroll Setup & Bookkeeping Sync for NJ Small Employers",
    description: "Payroll software for New Jersey small employers: what to set up, how payroll flows into your books, and the NJ filings that follow every payroll.",
    intro: "Running payroll is more than paying people. Every payroll creates tax deposits, quarterly reports and entries in your books. We help small New Jersey employers set up a payroll service (Gusto is a common one) and keep the books in sync with it.",
    fits: ["New employers running payroll for the first time", "Owners who pay themselves through an S corporation", "Businesses whose payroll entries never match their bank account"],
    work: ["Helping you register as an NJ employer and choose a payroll service", "Recording each payroll in your books so wages, taxes and liabilities tie out", "Reconciling payroll tax payments to the liability accounts", "Tracking quarterly filings and year-end W-2 and 1099 deadlines", "Payroll processing and NJ filings as an add-on service"],
    watch: ["Most payroll services file and pay federal and NJ taxes for you, but you still have to review the reports. Mistakes stay with the employer.", "Contractors and employees are treated differently. Misclassifying workers can be expensive. See our contractor checklist.", "Check the payroll service's current pricing and which NJ filings are included."],
    faqs: [["Do you run payroll for us?", "We can process payroll and prepare NJ payroll filings as an add-on to bookkeeping. Pricing is on the bookkeeping page."], ["Does payroll software replace a bookkeeper?", "No. It calculates and files payroll. Someone still has to make sure it is recorded correctly in the books and reconciled."], ["Are you affiliated with Gusto?", "No. MCC Solutions is an independent firm. Gusto is a trademark of its owner."]],
    guides: ["nj-payroll-taxes-and-filings-for-small-employers", "1099-contractors-checklist-for-nj-businesses", "what-to-send-your-bookkeeper-each-month"],
  },
  {
    slug: "square-and-stripe", name: "Square, Stripe and payment processors", short: "Square & Stripe",
    title: "Reconciling Square, Stripe & PayPal Sales in Your Books",
    description: "How sales from Square, Stripe, PayPal and other processors should flow into your accounting software, and why deposits never match sales.",
    intro: "If you take card payments, your bank deposits will rarely match your sales. Processors keep fees, hold funds and batch payouts. Getting this right is what makes retail, restaurant and online-service books actually accurate.",
    fits: ["Retail shops, restaurants, salons and service businesses taking cards", "Online sellers using Stripe, Shopify Payments or PayPal", "Owners whose reported sales do not match their deposits"],
    work: ["Recording gross sales, fees, refunds and tips separately", "Reconciling processor payouts to bank deposits", "Setting up sales tax collected as a liability", "Handling chargebacks and held funds", "Monthly reports that show true sales and true fees"],
    watch: ["Recording only the net deposit hides processing fees and understates sales.", "Sales tax collected on card sales is a liability, not income.", "Payout timing causes month-end differences. A good reconciliation explains them."],
    faqs: [["Why don't my deposits match my sales?", "Processors deduct fees, hold reserves, subtract refunds and pay out in batches. The books need to record each piece."], ["Can you connect Square or Stripe to my accounting software?", "Yes, through the processor's connections or an import, depending on your setup."], ["Are you affiliated with these companies?", "No. MCC Solutions is an independent firm."]],
    guides: ["nj-sales-tax-for-small-businesses", "how-to-reconcile-a-bank-account", "what-to-send-your-bookkeeper-each-month"],
  },
];

const GUIDES = [
  {
    slug: "what-is-a-quickbooks-proadvisor", title: "What is a QuickBooks ProAdvisor?", updated: "2026-10-07",
    description: "What a QuickBooks ProAdvisor is, what certification does and does not mean, how to find one, and the questions to ask before you hire a bookkeeper.",
    intro: "You may have seen \"ProAdvisor\" on a bookkeeper's website. Here is what it means, what it does not mean, and how to use it when you are choosing help.",
    software: ["quickbooks-online"],
    sections: [
      ["What ProAdvisor means", [
        "ProAdvisor is Intuit's program for accountants and bookkeepers who work with QuickBooks. Members get training, software access and a listing in Intuit's Find a ProAdvisor directory, where small businesses can search for help.",
        "Joining the program and passing certification exams are two different things. Ask which a person has.",
      ]],
      ["What it does not mean", [
        "It is not a license. A ProAdvisor is not automatically a CPA, an enrolled agent or an attorney, and the title does not authorize anyone to give tax or legal advice. In New Jersey, only a licensed CPA can call themselves a CPA, and anyone paid to prepare tax returns needs a PTIN.",
        "It also is not a guarantee of quality. It tells you someone has chosen to specialize in QuickBooks. Their references and their work are what tell you the rest.",
      ]],
      ["Bookkeeper, ProAdvisor, accountant: which do you need?", [
        "A bookkeeper records and reconciles transactions. An accountant interprets the numbers, plans taxes and prepares returns. A ProAdvisor can be either. Most small businesses need a bookkeeper every month and a tax professional once a year. See our guide on the difference between a bookkeeper, accountant and CPA.",
      ]],
      ["How to find and check one", [
        "Search Intuit's Find a ProAdvisor directory by location, or ask your accountant for a referral. Whoever you talk to, ask these questions: Which QuickBooks products do you use daily? Which certifications do you hold, and can I see the listing? Who owns the QuickBooks account? Who is my backup if you are out? What exactly will I get each month?",
      ]],
      ["Red flags", [
        "Anyone who wants to be the account owner of your QuickBooks file. Anyone who asks for your online banking password. Anyone who promises a specific tax result. Anyone who cannot say what they will deliver each month.",
      ]],
    ],
    faqs: [["Is a ProAdvisor better than a regular bookkeeper?", "Not automatically. Certification shows training on the product. Experience with businesses like yours matters just as much."], ["Do ProAdvisors cost more?", "Rates vary widely by experience and scope. Ask for a written quote."], ["Is MCC Solutions a ProAdvisor?", "We do not claim any software certification on this site. We are an independent bookkeeping firm in Cranford and we are happy to explain how we work and who does the work."]],
  },
  {
    slug: "bookkeeper-vs-accountant-vs-cpa", title: "Bookkeeper vs. accountant vs. CPA: who do you need?", updated: "2026-10-07",
    description: "The difference between a bookkeeper, an accountant, a CPA and an enrolled agent for a New Jersey small business, and when each one is worth paying for.",
    intro: "The titles overlap, and they are not regulated the same way. Here is a plain version of who does what.",
    software: ["quickbooks-online", "xero"],
    sections: [
      ["Bookkeeper", ["A bookkeeper records the daily financial activity: categorizing transactions, reconciling accounts, tracking bills and invoices, and producing monthly reports. The goal is accurate books you can rely on. Bookkeeping does not require a license in New Jersey."]],
      ["Accountant", ["An accountant works with the numbers the bookkeeper produces: reviewing them, advising on structure and tax planning, and often preparing returns. \"Accountant\" is a general term, so ask about credentials."]],
      ["CPA", ["A Certified Public Accountant is licensed by the state. CPAs can prepare and review financial statements, represent clients before the IRS, and provide tax advice. If you need an audit, a review, or a formal opinion on financial statements, you need a CPA."]],
      ["Enrolled agent", ["An enrolled agent is a federally authorized tax professional who can represent taxpayers before the IRS. Many small businesses use an enrolled agent for tax planning and returns."]],
      ["What most small businesses do", ["Use a bookkeeper every month to keep books current, and a CPA or enrolled agent once or twice a year for taxes and planning. Clean books make the tax professional faster and cheaper. MCC Solutions provides the bookkeeping side and works alongside your tax preparer. We do not prepare tax returns."]],
    ],
    faqs: [["Can my bookkeeper do my taxes?", "Only if they are qualified and registered to prepare returns. Ask. Many small businesses use a separate tax professional."], ["Do I need a CPA if I have a bookkeeper?", "Most businesses still want a tax professional at least once a year, especially with employees, an S corporation election or multiple owners."]],
  },
  {
    slug: "how-to-set-up-bookkeeping-for-a-new-nj-llc", title: "How to set up bookkeeping for a new New Jersey LLC", updated: "2026-10-07",
    description: "A step-by-step setup for a new NJ LLC: business bank account, accounting software, chart of accounts, sales tax and payroll registration, and monthly habits.",
    intro: "A clean start saves hours of cleanup later. Here is the order we would set things up in for a new New Jersey LLC.",
    software: ["quickbooks-online", "wave"],
    sections: [
      ["1. Open a business bank account and card", ["Once the LLC is formed and you have an EIN, open a business checking account in the LLC's name and use it for every business transaction. Get a business credit card too, if you use one. This single step prevents most bookkeeping problems. See our guide on separating personal and business money."]],
      ["2. Register for the state taxes you need", ["Depending on what you do, you may need to register with the NJ Division of Revenue and Enterprise Services and the Division of Taxation: for sales tax if you sell taxable goods or services, and for employer withholding if you will have employees. The state's online business registration walks through it. Check the current requirements for your business type."]],
      ["3. Pick accounting software", ["Choose one program and start on day one. QuickBooks Online is the safe choice if you will work with an accountant. Xero, Wave and FreshBooks suit some businesses. Ask your tax preparer which they prefer before you pick."]],
      ["4. Set up a simple chart of accounts", ["Start with the defaults for your industry and add categories only when you need them. Too many categories make reports harder to read. See our chart of accounts guide."]],
      ["5. Connect your bank feeds and set a monthly routine", ["Connect the business bank and card accounts, categorize weekly or monthly, and reconcile every month against the statement. Keep receipts for larger purchases. Save a copy of your formation documents and EIN letter in a folder you can find."]],
      ["6. Mark the dates that matter", ["Put the annual report due date, quarterly payroll and sales tax deadlines, and your tax filing dates on a calendar. See the guide on the New Jersey annual report."]],
    ],
    faqs: [["Do I need a bookkeeper from day one?", "Not always. A very simple business can start on its own. But a setup session with a professional often saves more than it costs."], ["Can I use my personal bank account for the LLC?", "You can, but mixing makes books harder and can weaken the separation between you and the LLC. Open a business account."]],
  },
  {
    slug: "how-to-catch-up-on-behind-books", title: "How to catch up when your books are months behind", updated: "2026-10-07",
    description: "A practical plan for catching up on months or years of unreconciled bookkeeping: gather statements, reconcile in order, and fix the problems that cause delay.",
    intro: "Falling behind is common, and it is fixable. The method is the same whether you are three months behind or three years.",
    software: ["quickbooks-online"],
    sections: [
      ["Step 1: Decide the start date", ["Pick the earliest month you need accurate books. For taxes, that is the start of the tax year in question. Work forward from there rather than trying to fix everything at once."]],
      ["Step 2: Gather the source documents", ["Get statements for every business bank account, credit card, loan and payment processor for each month. If you are missing any, download them from the institution's website. Collect payroll reports, sales tax filings and any records of cash transactions."]],
      ["Step 3: Check the opening balances", ["The first month has to start from the right balances. If the software shows a balance that does not match the statement, fix that first. Wrong opening balances cause errors in every month after."]],
      ["Step 4: Reconcile month by month, in order", ["Categorize each month's transactions, then reconcile to the statement ending balance before moving on. Do not skip ahead. If a month will not reconcile, find the difference now. Common causes are duplicate entries from a bank feed and a manual import, transfers recorded twice, and missing transactions."]],
      ["Step 5: Clean up the loose ends", ["Clear uncategorized and \"ask my accountant\" items, match payments to invoices and bills, and check loan balances, sales tax payable and payroll liabilities against actual filings and statements."]],
      ["Step 6: Keep it current", ["Once you are caught up, set a monthly rhythm. If you fell behind because it never gets done, that is the signal to hand it off. MCC Solutions offers cleanup projects with a written quote, followed by monthly bookkeeping."]],
    ],
    faqs: [["How much does a cleanup cost?", "It depends on the number of months, accounts and transactions, and the state of the file. We review first and give a written quote. Our bookkeeping page lists starting prices for cleanup."], ["Will the IRS care that I'm behind?", "Late tax filings can carry penalties regardless of your books. If you have unfiled returns, talk to a tax professional promptly."]],
  },
  {
    slug: "how-to-reconcile-a-bank-account", title: "How to reconcile a bank account (and why it matters)", updated: "2026-10-07",
    description: "A plain-language walkthrough of bank reconciliation in QuickBooks, Xero and other software: what it is, how to do it, and what to do when it will not balance.",
    intro: "Reconciliation is the check that says your books match reality. It is the most important monthly task in bookkeeping.",
    software: ["quickbooks-online", "xero", "square-and-stripe"],
    sections: [
      ["What reconciliation is", ["You compare the transactions in your accounting software to the bank or card statement, line by line, until the ending balance in the software matches the statement. Anything that does not match is either a recording error or a real problem you need to know about."]],
      ["How to do it", ["Open the reconcile screen for the account and enter the statement ending date and balance. Tick each transaction that appears on the statement. Add anything missing and fix anything wrong. When the difference reads zero, finish the reconciliation and save the report."]],
      ["Why it matters", ["Reconciled books catch fraud, duplicate charges, missed deposits and bank errors. Lenders, tax preparers and buyers trust numbers that reconcile."]],
      ["When it will not balance", ["Check for transactions entered twice, a transaction in the wrong account, a changed past entry, a missing deposit, and a typo in the statement balance. Look at the difference amount: if it equals one transaction, or half of one, you have found a likely cause."]],
      ["How often", ["Every month, for every bank account and credit card. Reconcile payment processor accounts such as Square or Stripe too."]],
    ],
    faqs: [["Do bank feeds make reconciliation unnecessary?", "No. Feeds import transactions. Reconciliation confirms nothing is missing, doubled or wrong."], ["Can you do this for me?", "Yes, it is the core of our monthly bookkeeping."]],
  },
  {
    slug: "nj-sales-tax-for-small-businesses", title: "New Jersey sales tax for small businesses", updated: "2026-10-07",
    description: "How New Jersey sales tax works for small businesses: when to register, what is taxable, how to collect and file, and how to record it in your books.",
    intro: "If you sell taxable goods or services in New Jersey, you collect sales tax for the state and send it in. This guide covers the basics. Check the NJ Division of Taxation for the rules on your specific products.",
    software: ["square-and-stripe", "quickbooks-online"],
    sections: [
      ["Do you need to register?", ["Businesses selling taxable goods or services in New Jersey generally need to register with the state and get a Certificate of Authority to collect sales tax before they begin. Many services are not taxable in New Jersey while many goods are, so check your specific products with the Division of Taxation or a tax professional."]],
      ["What is the rate?", ["The New Jersey state sales tax rate is 6.625%. There are limited special cases, such as urban enterprise zones with a reduced rate. Check the Division of Taxation for current rates and exemptions."]],
      ["How to collect it", ["Turn on sales tax in your point-of-sale or invoicing system and make sure taxable items are marked. Keep exemption certificates for customers who do not pay sales tax, such as resale certificates. Without one, you are expected to collect."]],
      ["How and when to file", ["Returns are filed online with the Division of Taxation, usually quarterly, though larger filers may be on a monthly schedule. Quarterly returns have been due on the 20th of the month after quarter end. Confirm your filing frequency and dates with the state."]],
      ["How it belongs in your books", ["Sales tax collected is not income. It sits in a liability account until you remit it. Record your sales net of tax and the tax separately, and reconcile the liability to what you filed. This is one of the most common books errors for card-based businesses."]],
    ],
    faqs: [["Do I charge sales tax on services?", "It depends on the service. Check the Division of Taxation's list for your type of service, or ask a tax professional."], ["What happens if I forget to file?", "Penalties and interest can apply, and you owe the tax even if you did not collect it. File as soon as you can and ask a tax professional about your options."]],
  },
  {
    slug: "nj-payroll-taxes-and-filings-for-small-employers", title: "New Jersey payroll taxes and filings for small employers", updated: "2026-10-07",
    description: "An overview of the federal and New Jersey payroll taxes a small employer pays and files, with the reports that follow each quarter and year.",
    intro: "Hiring your first employee brings a set of recurring tax tasks. This is an overview of what to expect. Confirm current forms and due dates with the IRS and the NJ Division of Taxation.",
    software: ["gusto-payroll"],
    sections: [
      ["Register as an employer", ["Before you pay wages, get an EIN from the IRS and register with the State of New Jersey as an employer for withholding and unemployment and disability insurance contributions. Keep the account numbers where your payroll service can use them."]],
      ["What comes out and what you add", ["From each paycheck you withhold federal income tax, Social Security and Medicare, and New Jersey income tax and certain state payroll contributions. As the employer, you also pay your share of Social Security and Medicare, federal and state unemployment taxes, and employer-side state contributions. The exact set depends on your business."]],
      ["The reports", ["Employers typically file a federal quarterly return (Form 941) and an annual federal unemployment return (Form 940), and file New Jersey quarterly returns and wage reports. At year end you provide Forms W-2 to employees and file them with the government. A payroll service can prepare and file these, and you remain responsible for accuracy."]],
      ["Deposits", ["Withheld taxes are deposited on a schedule that depends on how much you owe. Missed or late deposits are penalized. Set them up as automatic payments through your payroll service."]],
      ["How payroll fits in your books", ["Each payroll records gross wages as an expense, employer taxes as an expense, and amounts withheld as liabilities until paid. Reconcile the payroll liability accounts every quarter against your tax filings. When the numbers do not tie out, something is wrong."]],
      ["Common mistakes", ["Paying workers as contractors who should be employees. Paying yourself as an owner without understanding what your entity type allows. Forgetting NJ filings because the federal ones were automatic. Using personal funds for tax deposits."]],
    ],
    faqs: [["Can I run payroll myself?", "Yes, with a good payroll service. The risk is in the filings and reconciliations afterward. We can process payroll or just reconcile it."], ["When do I pay myself through payroll?", "Depends on your entity type and tax election. Ask your tax professional before you decide."]],
  },
  {
    slug: "1099-contractors-checklist-for-nj-businesses", title: "1099 contractors: a checklist for New Jersey businesses", updated: "2026-10-07",
    description: "A practical checklist for paying independent contractors: W-9 collection, 1099-NEC filing, worker classification and what to track during the year.",
    intro: "If you pay independent contractors, the paperwork starts before the first payment and ends in January. Here is a short checklist.",
    software: ["gusto-payroll", "quickbooks-online"],
    sections: [
      ["Before you pay: collect a W-9", ["Ask every contractor for a completed Form W-9 before the first payment. It gives you their legal name, tax classification and taxpayer ID, which you need to file. Do not wait until January to ask."]],
      ["Is the worker really a contractor?", ["Classification depends on the facts of the relationship, not on what you call it. New Jersey applies a strict test, so independent contractors generally need to be truly independent. If you control when, where and how the work is done, they may be an employee. Ask a tax professional or the Department of Labor if unsure."]],
      ["Track payments during the year", ["Mark vendors as 1099 vendors in your accounting software and record payments to them in the right categories. Payments by credit card or payment app are reported by the processor, not by you, so know which payments you must report."]],
      ["File in January", ["Form 1099-NEC is generally due to the contractor and the IRS by January 31 for the prior year. The dollar amount at which you must file has been $600 and has changed under recent legislation, so check the IRS instructions for the year you are filing. Certain states also require filings."]],
      ["Keep the records", ["Keep W-9s, invoices and proof of payment. They protect you if the classification is questioned later."]],
    ],
    faqs: [["Do I issue a 1099 to a corporation?", "Often not, with exceptions. Check the IRS instructions for your situation."], ["Can you prepare 1099s?", "We track 1099 vendors in your books and prepare the data. We can also help with filing, as an add-on."]],
  },
  {
    slug: "new-jersey-llc-annual-report", title: "New Jersey LLC annual report: what it is and when it is due", updated: "2026-10-07",
    description: "How the New Jersey annual report works for LLCs and corporations: who must file, when it is due, what it costs and what happens if you miss it.",
    intro: "Most New Jersey LLCs and corporations must file an annual report with the state. It is easy to forget and costly to ignore.",
    software: ["quickbooks-online"],
    sections: [
      ["Who files", ["New Jersey LLCs and corporations generally file an annual report with the Division of Revenue and Enterprise Services. Foreign entities registered to do business in New Jersey file as well. Check with the state for exemptions."]],
      ["When", ["The report is due by the end of the anniversary month of your formation or registration. The state sends a reminder to the email on file, so keep that address current."]],
      ["Cost", ["The state charges a filing fee, which has been $75 for most LLCs and corporations. Confirm the current fee on the state's site before you file."]],
      ["How to file", ["File online through the state's business portal using your entity ID. Make sure your registered agent and office information is correct. Keep a copy of the confirmation."]],
      ["If you miss it", ["Missing the report can lead to loss of good standing, and eventually revocation of the business. Banks and lenders may ask for a good-standing certificate. File as soon as you realize it was missed."]],
    ],
    faqs: [["Is the annual report the same as a tax return?", "No. It keeps the state's record of your business current. Tax returns go to the IRS and the NJ Division of Taxation."], ["Will you remind me?", "Our bookkeeping clients get reminders for annual reports and other filing dates."]],
  },
  {
    slug: "chart-of-accounts-for-small-business", title: "Chart of accounts for a small business: how to set one up", updated: "2026-10-07",
    description: "What a chart of accounts is, how many categories you actually need, and a clean starting structure for a small business.",
    intro: "The chart of accounts is the list of categories your transactions go into. A clean one makes reports readable. A messy one makes every report suspect.",
    software: ["quickbooks-online", "xero", "zoho-books"],
    sections: [
      ["What it is", ["Every transaction is assigned to an account: assets, liabilities, equity, income or expenses. The chart of accounts is the full list. Your profit and loss and balance sheet are built from it."]],
      ["Start small", ["Use your software's default chart for your industry, then remove unused accounts and add only what you need to see separately. Fifty to seventy accounts is plenty for most small businesses."]],
      ["Common structure", ["Income by type of revenue. Cost of goods sold for direct costs. Operating expenses grouped by purpose: rent, insurance, payroll, software, marketing, professional fees, travel and meals, vehicle. Separate liabilities for sales tax payable and payroll taxes. Owner draws or distributions in equity, not expenses."]],
      ["Mistakes to avoid", ["Using \"miscellaneous\" for everything. Creating a new account for every vendor. Putting owner spending in expenses. Mixing loan principal with expense."]],
      ["Ask your tax preparer", ["The categories should line up with the lines on your tax return. A short call with your preparer can save time at year end."]],
    ],
    faqs: [["Can I change my chart of accounts later?", "Yes. Merging or renaming accounts is simple in most programs, and a bookkeeper can restructure it."], ["Should I use classes or tags?", "Only if you track separate locations, projects or departments."]],
  },
  {
    slug: "how-long-to-keep-business-records", title: "What business records to keep, and for how long", updated: "2026-10-07",
    description: "A practical retention guide for small business tax and accounting records, with the general IRS time limits and what to keep forever.",
    intro: "Keeping everything forever is not practical, and throwing it away too soon is risky. Here are general guidelines. Check with your tax professional for your situation.",
    software: ["quickbooks-online"],
    sections: [
      ["The general IRS rule", ["The IRS generally recommends keeping records for three years from the date you file a return. It extends to six years if you left out more than 25% of your income, and indefinitely if you did not file or filed a fraudulent return. Records of bad debt deductions are typically kept for seven years."]],
      ["Employment tax records", ["Keep employment tax records for at least four years after the tax is due or paid, whichever is later. This includes payroll reports, deposits, W-4s and W-9s."]],
      ["Keep long-term", ["Formation documents, operating agreement, EIN letter, tax returns, annual financial statements, asset purchase records, loan documents and lease agreements. Keep property and equipment records until the limitations period ends for the year you dispose of them."]],
      ["Keep digitally", ["Scanned records are generally acceptable. Store them in a folder that is backed up, with consistent names like year, vendor and date. Photos of receipts attached to the transaction in your software work well."]],
      ["Do not forget state rules", ["New Jersey has its own retention expectations for tax records. Check the Division of Taxation guidance, and keep sales tax and payroll records longer when in doubt."]],
    ],
    faqs: [["Can I shred paper receipts after scanning?", "Generally yes if the scan is clear and complete, but ask your tax professional, especially for large purchases."], ["Where should I keep digital records?", "In a secure, backed-up cloud folder that you own, not only on one computer."]],
  },
  {
    slug: "how-to-switch-accounting-software", title: "How to switch accounting software and keep your history", updated: "2026-10-07",
    description: "How to move from one accounting program to another (Wave, QuickBooks, Xero and others): what carries over, what does not, and how to pick the cutover date.",
    intro: "Switching software is a project, not a button. Done well, you keep your history and gain cleaner books. Done badly, you create duplicate entries and wrong balances.",
    software: ["quickbooks-online", "xero", "wave"],
    sections: [
      ["Why people switch", ["Common reasons: an accountant who prefers another program, a need for payroll or inventory, outgrowing a simple tool, or a file that has become unusable."]],
      ["Pick the cutover date", ["Many people switch at the start of a month or a fiscal year. You then load opening balances as of that date and begin recording in the new program. Keep the old program's file, read-only, so you can look things up."]],
      ["What moves and what doesn't", ["Customers, vendors and the chart of accounts usually move through an export. Opening balances, open invoices and open bills have to be entered or imported. Full transaction history often does not convert cleanly, and many people choose to keep history in the old program and start fresh with balances."]],
      ["Do these before the switch", ["Reconcile every account in the old program through the cutover date. Clear or note open items. Export reports for the prior periods: profit and loss, balance sheet, customer and vendor balances, and the general ledger."]],
      ["After the switch", ["Reconcile again in the new program and compare opening balances to the old reports. Reconnect bank feeds, payment processors and payroll. Tell your tax preparer what changed."]],
    ],
    faqs: [["How long does a switch take?", "From days to a few weeks, depending on the size of the file and how clean it is."], ["Will I lose my data?", "Not if you export and keep the old file. We always keep the old records available."]],
  },
  {
    slug: "separating-personal-and-business-finances", title: "Separating personal and business money: why and how", updated: "2026-10-07",
    description: "Why mixing personal and business money causes bookkeeping and legal problems, and the simple steps to separate them.",
    intro: "Using one account for everything is the habit that creates the most cleanup work, and it can weaken the legal protection of an LLC or corporation.",
    software: ["wave", "quickbooks-online"],
    sections: [
      ["Why it matters", ["Mixed accounts make every transaction a question: business or personal? Mistakes cost you deductions or create audit risk. For an LLC or corporation, mixing funds can also be used against the separation between you and the company if the business is sued."]],
      ["Open the right accounts", ["A business checking account in the company's name and a business credit card. Use them for every business expense and deposit. Pay yourself with owner draws or distributions or through payroll, depending on your entity."]],
      ["If you already mixed them", ["Go back and mark each transaction as business or personal. Record personal spending paid from the business as owner draws, and business spending paid personally as owner contributions or reimbursements. Then stop doing it."]],
      ["Handling the gray areas", ["Home office, vehicle use and phone bills have special rules. Keep records of business use and ask your tax preparer how to treat them."]],
      ["Monthly habit", ["Review the business account each month for anything personal. Move it out and record it correctly."]],
    ],
    faqs: [["Can I pay business expenses personally and reimburse myself?", "Yes, if you keep receipts and record the reimbursement. Paying from the business account directly is cleaner."], ["Does this apply to sole proprietors?", "Legal protection is not an issue, but your books will be cleaner and your deductions better supported."]],
  },
  {
    slug: "what-to-send-your-bookkeeper-each-month", title: "What to send your bookkeeper each month: a checklist", updated: "2026-10-07",
    description: "A monthly checklist of what your bookkeeper needs from you: statements, receipts, payroll reports, loan statements and answers to questions.",
    intro: "Monthly bookkeeping goes fastest when the inputs arrive on time. This is the checklist we would give a new client.",
    software: ["quickbooks-online", "square-and-stripe"],
    sections: [
      ["Access, not passwords", ["Give your bookkeeper user access to your accounting software and read-only access to the bank where possible. Do not share your personal logins or online banking passwords by email or text."]],
      ["Statements", ["Statements for every business bank account, credit card, loan and payment processor, by the 5th to 10th of the next month."]],
      ["Receipts and documents", ["Receipts for larger purchases, invoices you issued outside the software, and contracts or loan paperwork for new commitments."]],
      ["Payroll and tax", ["Payroll reports for the month, copies of tax notices, and sales tax or payroll filings made outside your accounting software."]],
      ["Questions", ["Expect a short list of transactions the bookkeeper could not categorize. Answer within a few days. Quick answers keep the books current."]],
      ["What you should get back", ["Reconciled accounts, a profit and loss, a balance sheet, and a short note about what changed or needs attention."]],
    ],
    faqs: [["What if I miss a month?", "Send it when you can. The longer you wait, the harder it is to remember what the transactions were."], ["How do I send documents securely?", "Through your client account on our site or the accounting software's attachment feature, rather than plain email."]],
  },
];

module.exports = { SOFTWARE, GUIDES };
