// Content for the location and service landing pages (src/seo.js renders them).
// Edit freely: every county and service here becomes its own page and sitemap entry.

const COUNTIES = [
  { slug: "atlantic", name: "Atlantic", seat: "Mays Landing", region: "South Jersey",
    towns: ["Atlantic City", "Egg Harbor Township", "Galloway", "Hammonton", "Pleasantville", "Absecon", "Ventnor City", "Margate City", "Somers Point", "Brigantine", "Linwood", "Northfield"],
    note: "Many shore and second-home owners in Atlantic County live out of state, so seller packages often close by RON or with a signer we meet locally while the owner signs remotely. Casino and hospitality schedules mean evening and weekend appointments are common here.",
    neighbors: ["cape-may", "cumberland", "gloucester", "camden", "burlington", "ocean"] },
  { slug: "bergen", name: "Bergen", seat: "Hackensack", region: "North Jersey",
    towns: ["Hackensack", "Teaneck", "Fort Lee", "Paramus", "Englewood", "Fair Lawn", "Garfield", "Lodi", "Mahwah", "Ridgewood", "Bergenfield", "Cliffside Park"],
    note: "Bergen County signings often happen in high-rise buildings in Fort Lee and Cliffside Park, where agents plan for concierge check-in and limited parking. With so many New York commuters, evening refinance signings are routine.",
    neighbors: ["passaic", "hudson", "essex"] },
  { slug: "burlington", name: "Burlington", seat: "Mount Holly", region: "South Jersey",
    towns: ["Moorestown", "Mount Laurel", "Marlton (Evesham)", "Cinnaminson", "Burlington City", "Willingboro", "Medford", "Bordentown", "Lumberton", "Pemberton", "Delran", "Maple Shade"],
    note: "Joint Base McGuire-Dix-Lakehurst sits partly in Burlington County, so we see powers of attorney and estate documents for service members before deployment or a move, along with steady refinance and purchase closings in the Route 73 and Route 38 suburbs.",
    neighbors: ["ocean", "monmouth", "mercer", "camden", "atlantic"] },
  { slug: "camden", name: "Camden", seat: "Camden", region: "South Jersey",
    towns: ["Cherry Hill", "Camden", "Gloucester Township", "Voorhees", "Pennsauken", "Haddonfield", "Collingswood", "Winslow", "Lindenwold", "Haddon Township", "Berlin", "Bellmawr"],
    note: "Camden County sits across the river from Philadelphia, and many Pennsylvania title companies and lenders need New Jersey signers here. We cover Cherry Hill, Voorhees and the Haddon towns daily, including evening closings.",
    neighbors: ["burlington", "gloucester", "atlantic"] },
  { slug: "cape-may", name: "Cape May", seat: "Cape May Court House", region: "South Jersey",
    towns: ["Ocean City", "Cape May", "Wildwood", "North Wildwood", "Wildwood Crest", "Sea Isle City", "Avalon", "Stone Harbor", "Lower Township", "Middle Township", "Upper Township", "Dennis Township"],
    note: "Cape May County is vacation-home country. Many owners live in Pennsylvania, New York or North Jersey, so we coordinate remote signings for absent owners and plan around summer traffic on the Garden State Parkway and the barrier islands.",
    neighbors: ["atlantic", "cumberland"] },
  { slug: "cumberland", name: "Cumberland", seat: "Bridgeton", region: "South Jersey",
    towns: ["Vineland", "Millville", "Bridgeton", "Upper Deerfield", "Deerfield", "Hopewell Township", "Fairfield", "Maurice River", "Commercial Township", "Lawrence Township"],
    note: "Cumberland County is spread out, with long drives between Vineland, Millville and the farm townships. Booking 24 hours ahead gives us the best agent match, and travel beyond 20 miles is quoted up front.",
    neighbors: ["salem", "gloucester", "atlantic", "cape-may"] },
  { slug: "essex", name: "Essex", seat: "Newark", region: "North Jersey",
    towns: ["Newark", "East Orange", "Irvington", "Bloomfield", "Montclair", "West Orange", "Livingston", "Belleville", "Nutley", "Maplewood", "South Orange", "Millburn"],
    note: "Newark is home to the county courthouse and many law firms, so Essex County work mixes attorney-ordered affidavits and estate signings with residential closings in Montclair, West Orange and Livingston. Hospital and rehab visits are frequent here too.",
    neighbors: ["passaic", "bergen", "hudson", "union", "morris"] },
  { slug: "gloucester", name: "Gloucester", seat: "Woodbury", region: "South Jersey",
    towns: ["Washington Township", "Deptford", "Monroe Township", "Glassboro", "West Deptford", "Mantua", "Woolwich", "Harrison Township", "Woodbury", "Pitman", "Logan Township", "Franklin Township"],
    note: "Gloucester County keeps adding new-construction neighborhoods in Woolwich, Harrison and Monroe, which means a steady flow of buyer purchase closings alongside refinances. Philadelphia-area title companies order here often.",
    neighbors: ["salem", "camden", "atlantic", "cumberland"] },
  { slug: "hudson", name: "Hudson", seat: "Jersey City", region: "North Jersey",
    towns: ["Jersey City", "Hoboken", "Bayonne", "Union City", "North Bergen", "West New York", "Kearny", "Secaucus", "Weehawken", "Harrison", "Guttenberg", "East Newark"],
    note: "Hudson County signings are mostly condos and high-rises in Jersey City, Hoboken and the Gold Coast. Agents allow extra time for building access and street parking, and evening appointments suit the many signers who work in Manhattan.",
    neighbors: ["bergen", "essex", "union"] },
  { slug: "hunterdon", name: "Hunterdon", seat: "Flemington", region: "Central Jersey",
    towns: ["Flemington", "Clinton", "Readington", "Raritan Township", "Lebanon", "Tewksbury", "Lambertville", "Frenchtown", "High Bridge", "Union Township", "Bethlehem Township", "East Amwell"],
    note: "Hunterdon County is rural, with estate homes and farms spread across long country roads. We schedule ahead, confirm directions with the signer, and quote travel past 20 miles before the appointment.",
    neighbors: ["warren", "morris", "somerset", "mercer"] },
  { slug: "mercer", name: "Mercer", seat: "Trenton", region: "Central Jersey",
    towns: ["Trenton", "Princeton", "Hamilton", "Ewing", "Lawrence", "West Windsor", "Robbinsville", "Hopewell", "East Windsor", "Hightstown", "Pennington"],
    note: "Trenton is the state capital and Princeton draws students, faculty and families from around the world. That means state paperwork, international documents that need remote notarization, and a busy residential market in Hamilton and West Windsor.",
    neighbors: ["hunterdon", "somerset", "middlesex", "monmouth", "burlington"] },
  { slug: "middlesex", name: "Middlesex", seat: "New Brunswick", region: "Central Jersey",
    towns: ["Edison", "Woodbridge", "New Brunswick", "Piscataway", "Old Bridge", "East Brunswick", "Perth Amboy", "Sayreville", "North Brunswick", "South Brunswick", "Monroe Township", "Metuchen"],
    note: "Middlesex County is the center of our coverage. Same-day signings are usually available in Edison, Woodbridge, New Brunswick and the Brunswicks, along with hospital and senior-community visits in Monroe Township.",
    neighbors: ["union", "somerset", "mercer", "monmouth"] },
  { slug: "monmouth", name: "Monmouth", seat: "Freehold", region: "Central Jersey",
    towns: ["Middletown", "Freehold", "Howell", "Manalapan", "Marlboro", "Long Branch", "Red Bank", "Asbury Park", "Holmdel", "Wall", "Neptune", "Ocean Township"],
    note: "Monmouth County mixes shore towns with large suburbs. We handle purchase and refinance closings from Middletown to Wall, and estate signings for retirees in Manalapan and the Freehold area.",
    neighbors: ["middlesex", "mercer", "burlington", "ocean"] },
  { slug: "morris", name: "Morris", seat: "Morristown", region: "North Jersey",
    towns: ["Morristown", "Parsippany-Troy Hills", "Randolph", "Rockaway", "Denville", "Madison", "Mount Olive", "Roxbury", "Montville", "Florham Park", "Chatham", "Morris Township"],
    note: "Morris County has many corporate offices along I-287 and Route 10, so business documents and I-9 verifications sit alongside residential closings in Randolph, Parsippany and the Chathams.",
    neighbors: ["sussex", "passaic", "essex", "union", "somerset", "hunterdon", "warren"] },
  { slug: "ocean", name: "Ocean", seat: "Toms River", region: "Central Jersey",
    towns: ["Toms River", "Lakewood", "Brick", "Jackson", "Manchester", "Point Pleasant", "Stafford", "Barnegat", "Berkeley", "Lacey", "Little Egg Harbor", "Long Beach Island"],
    note: "Ocean County has many adult and retirement communities, so wills, powers of attorney and healthcare directives make up much of our work here, alongside fast-growing purchase activity in Lakewood and Jackson.",
    neighbors: ["monmouth", "burlington", "atlantic"] },
  { slug: "passaic", name: "Passaic", seat: "Paterson", region: "North Jersey",
    towns: ["Paterson", "Clifton", "Passaic", "Wayne", "West Milford", "Little Falls", "Totowa", "Hawthorne", "Woodland Park", "Pompton Lakes", "Haledon", "Ringwood"],
    note: "Passaic County runs from dense Paterson, Clifton and Passaic up to the lake communities of West Milford and Ringwood. We plan longer travel for the northern townships and offer evening appointments in the cities.",
    neighbors: ["sussex", "morris", "essex", "bergen"] },
  { slug: "salem", name: "Salem", seat: "Salem", region: "South Jersey",
    towns: ["Pennsville", "Carneys Point", "Salem", "Pittsgrove", "Woodstown", "Penns Grove", "Upper Pittsgrove", "Mannington", "Alloway", "Elmer"],
    note: "Salem County is rural and sits just across the Delaware Memorial Bridge, so Delaware title companies often need New Jersey signers here. Booking a day ahead helps us match the closest agent.",
    neighbors: ["gloucester", "cumberland"] },
  { slug: "somerset", name: "Somerset", seat: "Somerville", region: "Central Jersey",
    towns: ["Franklin Township", "Bridgewater", "Hillsborough", "Somerville", "Basking Ridge (Bernards)", "Bound Brook", "Branchburg", "Montgomery", "North Plainfield", "Warren", "Raritan", "Manville"],
    note: "Somerset County is close to our home base, with same-day availability in Bridgewater, Somerville and Franklin. Corporate campuses in Basking Ridge and Warren also bring business and employment documents.",
    neighbors: ["hunterdon", "morris", "union", "middlesex", "mercer"] },
  { slug: "sussex", name: "Sussex", seat: "Newton", region: "North Jersey",
    towns: ["Newton", "Vernon", "Hopatcong", "Sparta", "Hardyston", "Byram", "Franklin", "Wantage", "Hamburg", "Stanhope", "Andover", "Frankford"],
    note: "Sussex County is lake and mountain country, with homes around Lake Hopatcong and in Vernon and Sparta. Distances are long, so we book ahead and quote travel past 20 miles up front.",
    neighbors: ["warren", "morris", "passaic"] },
  { slug: "union", name: "Union", seat: "Elizabeth", region: "North Jersey",
    towns: ["Elizabeth", "Union", "Plainfield", "Linden", "Westfield", "Cranford", "Summit", "Rahway", "Scotch Plains", "Hillside", "Roselle", "Springfield"],
    note: "Union County sits between our central base and North Jersey, so same-day coverage is common in Westfield, Cranford, Summit and Elizabeth. We handle residential closings, estate signings and hospital visits across the county.",
    neighbors: ["essex", "morris", "somerset", "middlesex", "hudson"] },
  { slug: "warren", name: "Warren", seat: "Belvidere", region: "North Jersey",
    towns: ["Phillipsburg", "Hackettstown", "Washington", "Belvidere", "Lopatcong", "Mansfield", "Independence", "Blairstown", "Greenwich", "Pohatcong"],
    note: "Warren County borders Pennsylvania's Lehigh Valley, and many Easton and Allentown title companies need New Jersey signers in Phillipsburg and nearby townships. We schedule ahead for the rural northern towns.",
    neighbors: ["sussex", "morris", "hunterdon"] },
];

const SERVICES = [
  { slug: "loan-signing-agent", code: "LOAN SIGNINGS", name: "Loan Signing Agents", short: "Loan signing agent",
    title: "Loan Signing Agent in New Jersey | Mobile Closings",
    description: "Certified loan signing agents for purchase, refinance, HELOC and reverse mortgage closings across New Jersey. Evening and weekend signings, scanbacks tracked.",
    h1: "Loan signing agents across New Jersey",
    lede: "MCC Solutions sends certified, background-screened signing agents to borrowers' homes, offices and anywhere else they need to sign. Title companies, lenders and attorneys get one desk that confirms the agent, tracks the documents and sends the return tracking number.",
    included: ["Purchase (buyer and seller), refinance, HELOC, reverse mortgage and loan modification packages", "Printing of e-docs, letter and legal, with a second borrower set on request", "A full page check at the table for signatures, initials and dates", "Scanbacks reviewed by the desk before the package ships", "Drop-off with your prepaid FedEx or UPS label and the tracking number sent to you"],
    who: ["Title and escrow companies, in New Jersey and out of state", "Lenders and mortgage brokers", "Real estate attorneys", "Signing services that need New Jersey coverage"],
    faqs: [
      ["How quickly can you assign a signing agent?", "During desk hours we confirm most orders within 15 minutes. Same-day signings are often possible in central and North Jersey; 24 hours of notice gives the best agent match statewide."],
      ["Do your agents print the documents?", "Yes. Agents print e-docs on dual-tray laser printers. Tell us if the borrower needs a second set."],
      ["Can the signing agent explain the loan terms?", "No. Signing agents cannot give legal or financial advice. Questions about the loan go to the lender or closing attorney, and the agent can help the borrower reach them during the signing."],
    ] },
  { slug: "mobile-notary", code: "GENERAL NOTARY", name: "Mobile Notary", short: "Mobile notary",
    title: "Mobile Notary in New Jersey | We Come to You",
    description: "A New Jersey mobile notary at your home, office, hospital or job site. Affidavits, powers of attorney, vehicle titles and business documents. Book online.",
    h1: "A mobile notary that comes to you, anywhere in New Jersey",
    lede: "Skip the trip to the bank. A commissioned New Jersey notary meets you at home, at work or at a care facility, checks your ID and notarizes your documents on the spot. The travel and service fee is quoted before we confirm.",
    included: ["Acknowledgments, jurats, oaths and affirmations", "Affidavits, powers of attorney, consent forms and vehicle titles", "Business documents, contracts and I-9 verifications", "Evening, weekend and same-day visits on request", "New Jersey's notarial fee of $2.50 per act, shown separately from travel"],
    who: ["Individuals and families", "Small businesses and HR teams", "Attorneys and their clients", "Car dealers and property managers"],
    faqs: [
      ["What do I need to bring?", "An unexpired government photo ID for every signer, and the documents unsigned. Signers sign in front of the notary."],
      ["How much does a mobile notary cost in New Jersey?", "New Jersey sets the notarial fee at $2.50 per act. The travel and service fee depends on distance and timing, and we quote it before confirming."],
      ["Can you prepare or fill out my documents?", "No. Notaries cannot draft documents or give legal advice. Bring completed documents, or have your attorney prepare them."],
    ] },
  { slug: "hospital-notary", code: "FACILITY", name: "Hospital & Care Facility Notary", short: "Hospital notary",
    title: "Hospital & Nursing Home Notary in New Jersey",
    description: "Mobile notary visits to New Jersey hospitals, nursing homes, rehab centers and hospice for powers of attorney, healthcare proxies and advance directives.",
    h1: "Hospital, nursing home and hospice notary visits in New Jersey",
    lede: "When a family member can't leave the bed, we bring the notary to them. MCC Solutions sends notaries to hospitals, rehab centers, assisted living, nursing homes and hospice care, including evenings and weekends.",
    included: ["Powers of attorney, healthcare proxies and advance directives", "Wills and estate documents, with witnesses arranged on request", "Coordination with social workers and case managers on visiting rules", "Evening, weekend and urgent same-day visits"],
    who: ["Families of patients and residents", "Hospital social workers and discharge planners", "Elder law and estate attorneys", "Assisted living and nursing home staff"],
    faqs: [
      ["What does the signer need?", "A current government photo ID and the ability to understand and willingly sign. If the signer has no ID, call the desk before booking so we can check your options."],
      ["Can the notary refuse to notarize?", "Yes. If the signer seems confused, heavily medicated or pressured, the notary must decline. A trip fee may still apply."],
      ["Can hospital staff act as witnesses?", "Many facilities don't allow staff to witness. Tell us if you need witnesses and we will bring them."],
    ] },
  { slug: "estate-planning-notary", code: "ESTATE", name: "Estate Planning Signings", short: "Wills & POA notary",
    title: "Wills, POA & Estate Signing Notary in New Jersey",
    description: "Mobile notary and witnesses for wills, powers of attorney, healthcare directives and trusts across New Jersey. At home, in the office or at a facility.",
    h1: "Notary and witnesses for wills, powers of attorney and trusts",
    lede: "Estate signings need the right people in the room. We bring a commissioned notary and, when needed, two witnesses to your client's home, office or care facility so the plan is signed correctly the first time.",
    included: ["Wills with witnesses and a notarized self-proving affidavit", "Durable and financial powers of attorney", "Healthcare proxies and advance directives", "Trust documents and deeds prepared by your attorney", "Visits at homes, offices, hospitals and senior communities"],
    who: ["Estate planning and elder law attorneys", "Families coordinating a parent's paperwork", "Financial advisors and trust officers"],
    faqs: [
      ["Do you provide witnesses?", "Yes, on request. Wills usually need two witnesses who are not beneficiaries. Let us know when you book."],
      ["Can you draft a will or power of attorney?", "No. Documents must be prepared by the signer or their attorney. We handle the signing, notarization and witnesses."],
    ] },
  { slug: "remote-online-notarization", code: "RON", name: "Remote Online Notarization (RON)", short: "Remote online notary",
    title: "Remote Online Notarization (RON) in New Jersey",
    description: "Notarize documents online over secure video with a New Jersey notary. ID verification, electronic seal and a recorded session. Book a RON session.",
    h1: "Remote Online Notarization with a New Jersey notary",
    lede: "Sign and notarize from anywhere over secure two-way video. The signer's identity is verified online, documents are signed electronically, and the notary applies an electronic seal. The session is recorded and kept as the law requires.",
    included: ["ID scan and identity questions before the session", "Electronic signatures and a tamper-evident electronic seal", "A recorded session, retained as the law requires", "Signers out of state and, for many documents, outside the U.S."],
    who: ["Signers who can't meet in person", "Expats, military families and travelers", "Title companies and lenders that accept RON closings", "Businesses with signers in several states"],
    faqs: [
      ["What do I need for a RON session?", "An unexpired government photo ID, a computer or tablet with a camera and microphone, and a stable internet connection."],
      ["Will my lender or the receiving party accept it?", "Most do, but acceptance depends on the lender, title underwriter or agency. We confirm before scheduling."],
    ] },
  { slug: "remote-ink-signed-notarization", code: "RIN", name: "Remote Ink-Signed Notarization (RIN)", short: "Remote ink notarization",
    title: "Remote Ink-Signed Notarization (RIN) in New Jersey",
    description: "Sign paper documents in wet ink on live video with a New Jersey notary, then ship the originals for the notary to complete. When paper originals are required.",
    h1: "Remote Ink-Signed Notarization when you need paper originals",
    lede: "Some documents still need wet-ink signatures. With RIN, the signer signs the paper documents on live video while the notary watches, ships the originals, and the notary completes the certificate when they arrive.",
    included: ["Live video signing of paper documents", "Shipping instructions and tracking for the originals", "Notary completes and seals the paper certificate", "Eligibility check for your state and document before booking"],
    who: ["Signers whose documents require wet ink", "Out-of-state owners selling New Jersey property", "Attorneys who need paper originals"],
    faqs: [
      ["Why isn't RIN available everywhere?", "Most temporary RIN rules from 2020 and 2021 have ended, and only a few states have permanent rules. We check eligibility for each order."],
      ["How long does RIN take?", "The video signing takes about 30 minutes. The notary finishes once the originals arrive, usually one to three business days later."],
    ] },
  { slug: "apostille-services", code: "APOSTILLE", name: "Apostille Services", short: "Apostille services",
    title: "Apostille Services in New Jersey | Notarize & Apostille",
    description: "We notarize your documents and handle the New Jersey apostille request for use abroad: powers of attorney, affidavits, school and business documents.",
    h1: "Notarization and New Jersey apostilles, handled for you",
    lede: "Documents headed to another country often need an apostille, the state certificate that confirms the notary's signature. MCC Solutions notarizes your document, prepares the request to New Jersey's Division of Revenue and Enterprise Services, and gets the finished document back to you.",
    included: ["Notarization by a New Jersey notary, with original ink signatures, as the state requires", "Preparing and submitting the apostille request to the NJ Division of Revenue and Enterprise Services", "Help ordering certified vital records from the NJ Department of Health when a birth or marriage record is involved", "A heads-up when a non-English document needs a notarized English translation first", "The state fee and our service fee quoted up front, before we start"],
    who: ["People working, studying or marrying abroad", "Families completing international adoptions", "Businesses opening accounts or companies overseas", "Expats who need a New Jersey power of attorney used abroad"],
    faqs: [
      ["What is an apostille?", "A certificate from the state that confirms a notary's or public official's signature, so the document is accepted in countries that follow the Hague Apostille Convention."],
      ["Can every document get a New Jersey apostille?", "New Jersey apostilles cover documents notarized by a New Jersey notary and records signed by certain New Jersey officials. Federal documents, such as an FBI background check, go through the U.S. Department of State instead. We'll tell you which applies before you pay."],
      ["How long does it take?", "It depends on the state's processing time and shipping. We give you an estimate when you order and keep you posted until the document is back in your hands."],
    ] },
  { slug: "private-lender-signings", code: "INVESTOR LOANS", name: "Private & Investor Loan Signings", short: "Private lender signings",
    title: "Private & Investor Loan Signings in New Jersey",
    description: "Signing agents for hard money, fix-and-flip, DSCR rental and business-purpose loans across NJ. LLC and guarantor signings, evening closings, fast scanbacks.",
    h1: "Signing agents for private and investor loans in New Jersey",
    lede: "Private lenders move fast and close on tight funding deadlines. MCC Solutions sends certified signing agents for bridge, fix-and-flip, DSCR rental, construction and other business-purpose loans, with scanbacks reviewed before release.",
    included: ["Bridge, fix-and-flip, DSCR rental, construction and other business-purpose loan packages", "Entity signings: the notary verifies each signer's identity, and your package documents their authority to sign for the LLC", "Several guarantors or members signed at one visit", "Same-day and evening closings to meet funding deadlines", "Scanbacks reviewed by the desk before release; originals shipped with your label"],
    who: ["Private and hard money lenders", "Investor-focused mortgage brokers", "Attorneys closing private loans", "Title companies handling investor transactions"],
    faqs: [
      ["Can you close a borrower who lives out of state?", "Yes. If the lender accepts remote online notarization we can close by video; otherwise we arrange a signing near the borrower."],
      ["How fast can you get a signer out?", "Same-day is often possible in central and North Jersey. Send the order as early as you can and we'll confirm the agent and time."],
    ] },
  { slug: "usps-form-1583", code: "FORM 1583", name: "USPS Form 1583 Notarization", short: "Form 1583 notarization",
    title: "Notarize USPS Form 1583 in NJ | Online or In Person",
    description: "Get USPS Form 1583 notarized for your virtual mailbox: online by video or with a mobile notary in New Jersey. Bring two IDs; done in minutes.",
    h1: "Get your USPS Form 1583 notarized, online or in person",
    lede: "Opening a virtual mailbox usually means USPS Form 1583, the authorization for an agent to receive your mail, and many mailbox providers require it notarized. MCC Solutions notarizes it by secure video from anywhere, or sends a mobile notary to you in New Jersey.",
    included: ["Remote online notarization from anywhere, usually in minutes", "Mobile notary visits in New Jersey, including evenings", "A quick check that your form is complete before you sign", "A notarized copy ready to upload to your mailbox provider", "Business accounts for virtual office and mailbox providers that refer customers"],
    who: ["Virtual mailbox customers", "New LLC owners and remote businesses", "Travelers, RVers and expats", "Virtual office, coworking and mailbox providers"],
    faqs: [
      ["What ID do I need?", "Form 1583 asks for two forms of identification, one with a photo. Have both ready, along with the completed form, unsigned."],
      ["Does my mailbox provider require notarization?", "Many do, but some verify your ID themselves. Check your provider's instructions before booking."],
      ["Who signs for a business?", "An authorized officer of the business signs the form for the company, and each person receiving mail at the address may need their own form. Your provider will tell you what they need."],
    ] },
  { slug: "child-travel-consent", code: "TRAVEL", name: "Child Travel Consent Notarization", short: "Child travel consent",
    title: "Notarized Child Travel Consent Letters in New Jersey",
    description: "Notarize a minor travel consent letter when a child travels abroad with one parent, relatives or a school group. Mobile and online options in New Jersey.",
    h1: "Notarized travel consent letters for children traveling abroad",
    lede: "When a child travels internationally without both parents, a signed and notarized consent letter from the parent who isn't traveling can prevent problems at the border or the airport. MCC Solutions notarizes it at your home or office, or online if a parent is away.",
    included: ["Notarization of the consent letter signed by the parent or parents who aren't traveling", "Remote online notarization when a parent is out of town or overseas", "An apostille arranged when the destination country asks for one", "Evening and weekend appointments before trips"],
    who: ["A parent traveling alone with children", "Grandparents and other relatives", "School, sports and church groups", "Divorced or separated parents"],
    faqs: [
      ["Is a consent letter required?", "U.S. Customs and Border Protection recommends one when a child travels without both parents, and some countries and airlines require a notarized letter. Check your destination and airline before you go."],
      ["Can you write the letter for me?", "Notaries can't draft documents. Bring your completed letter, unsigned, and every signing parent's photo ID."],
    ] },
  { slug: "business-notary", code: "BUSINESS", name: "Business & Dealer Notary Services", short: "Business notary",
    title: "Business & Auto Dealer Notary Services in New Jersey",
    description: "Mobile notary accounts for NJ auto dealers, property managers, HR teams, contractors, insurers and funeral homes. On-site visits, monthly invoicing.",
    h1: "Notary services for New Jersey businesses",
    lede: "Dealerships, property managers, HR teams and other businesses need documents notarized every week. Open a business account and MCC Solutions sends a commissioned notary to your office, lot or job site, or to your customer, and bills you once a month.",
    included: ["On-site visits at your office, dealership, job site or a customer's home", "Notarization for out-of-state buyers and customers who can't come in", "Remote online notarization for signers who are out of state or traveling", "One business account: online ordering, status updates and monthly invoices", "Standing instructions saved to your account, so every visit is done your way"],
    who: ["Auto dealers: title and registration paperwork, powers of attorney, out-of-state buyers", "Property managers and landlords: leases, affidavits, estoppel certificates", "HR and staffing teams: I-9 verifications and employment documents", "Contractors: lien waivers, contracts and affidavits", "Insurance and public adjusters: sworn proofs of loss, often at the property", "Funeral homes: affidavits and estate paperwork for families", "Banks, credit unions, accountants and financial advisors: overflow and homebound clients"],
    faqs: [
      ["How does billing work for businesses?", "Business accounts get one invoice a month for every visit, payable by ACH or card. Each line shows the notarial fee separately from the service and travel fee."],
      ["Can a notary come to our customer instead of our office?", "Yes. We send the notary wherever the signer is: home, hospital, job site or another office. You place the order; we confirm the time with the signer."],
      ["Can you prepare our documents?", "No. Notaries can't draft documents or give legal advice. Send completed documents, and we handle the signing and notarization."],
    ] },
];

module.exports = { COUNTIES, SERVICES };
