// Content for the location and service landing pages (src/seo.js renders them).
// Edit freely: every county and service here becomes its own page and sitemap entry.

const COUNTIES = [
  { slug: "atlantic", name: "Atlantic", seat: "Mays Landing", region: "South Jersey",
    towns: ["Atlantic City", "Egg Harbor Township", "Galloway", "Hammonton", "Pleasantville", "Absecon", "Ventnor City", "Margate City", "Somers Point", "Brigantine", "Linwood", "Northfield"],
    note: "Many shore and second-home owners in Atlantic County live out of state, so seller packages often close by RON or with a signer we meet locally while the owner signs remotely. Casino and hospitality schedules mean evening and weekend appointments are common here.",
    neighbors: ["cape-may", "cumberland", "gloucester", "camden", "burlington", "ocean"] },
  { slug: "bergen", name: "Bergen", seat: "Hackensack", region: "North Jersey",
    towns: ["Hackensack", "Teaneck", "Fort Lee", "Paramus", "Englewood", "Fair Lawn", "Garfield", "Lodi", "Mahwah", "Ridgewood", "Bergenfield", "Cliffside Park"],
    note: "Bergen County signings often happen in high-rise buildings in Fort Lee and Cliffside Park, where agents plan for concierge check-in and limited parking. With so many New York commuters, evening refinance signings are routine.",
    neighbors: ["passaic", "hudson", "essex"] },
  { slug: "burlington", name: "Burlington", seat: "Mount Holly", region: "South Jersey",
    towns: ["Moorestown", "Mount Laurel", "Marlton (Evesham)", "Cinnaminson", "Burlington City", "Willingboro", "Medford", "Bordentown", "Lumberton", "Pemberton", "Delran", "Maple Shade"],
    note: "Joint Base McGuire-Dix-Lakehurst sits partly in Burlington County, so we see powers of attorney and estate documents for service members before deployment or a move, along with steady refinance and purchase closings in the Route 73 and Route 38 suburbs.",
    neighbors: ["ocean", "monmouth", "mercer", "camden", "atlantic"] },
  { slug: "camden", name: "Camden", seat: "Camden", region: "South Jersey",
    towns: ["Cherry Hill", "Camden", "Gloucester Township", "Voorhees", "Pennsauken", "Haddonfield", "Collingswood", "Winslow", "Lindenwold", "Haddon Township", "Berlin", "Bellmawr"],
    note: "Camden County sits across the river from Philadelphia, and many Pennsylvania title companies and lenders need New Jersey signers here. We cover Cherry Hill, Voorhees and the Haddon towns daily, including evening closings.",
    neighbors: ["burlington", "gloucester", "atlantic"] },
  { slug: "cape-may", name: "Cape May", seat: "Cape May Court House", region: "South Jersey",
    towns: ["Ocean City", "Cape May", "Wildwood", "North Wildwood", "Wildwood Crest", "Sea Isle City", "Avalon", "Stone Harbor", "Lower Township", "Middle Township", "Upper Township", "Dennis Township"],
    note: "Cape May County is vacation-home country. Many owners live in Pennsylvania, New York or North Jersey, so we coordinate remote signings for absent owners and plan around summer traffic on the Garden State Parkway and the barrier islands.",
    neighbors: ["atlantic", "cumberland"] },
  { slug: "cumberland", name: "Cumberland", seat: "Bridgeton", region: "South Jersey",
    towns: ["Vineland", "Millville", "Bridgeton", "Upper Deerfield", "Deerfield", "Hopewell Township", "Fairfield", "Maurice River", "Commercial Township", "Lawrence Township"],
    note: "Cumberland County is spread out, with long drives between Vineland, Millville and the farm townships. Booking 24 hours ahead gives us the best agent match, and travel beyond 20 miles is quoted up front.",
    neighbors: ["salem", "gloucester", "atlantic", "cape-may"] },
  { slug: "essex", name: "Essex", seat: "Newark", region: "North Jersey",
    towns: ["Newark", "East Orange", "Irvington", "Bloomfield", "Montclair", "West Orange", "Livingston", "Belleville", "Nutley", "Maplewood", "South Orange", "Millburn"],
    note: "Newark is home to the county courthouse and many law firms, so Essex County work mixes attorney-ordered affidavits and estate signings with residential closings in Montclair, West Orange and Livingston. Hospital and rehab visits are frequent here too.",
    neighbors: ["passaic", "bergen", "hudson", "union", "morris"] },
  { slug: "gloucester", name: "Gloucester", seat: "Woodbury", region: "South Jersey",
    towns: ["Washington Township", "Deptford", "Monroe Township", "Glassboro", "West Deptford", "Mantua", "Woolwich", "Harrison Township", "Woodbury", "Pitman", "Logan Township", "Franklin Township"],
    note: "Gloucester County keeps adding new-construction neighborhoods in Woolwich, Harrison and Monroe, which means a steady flow of buyer purchase closings alongside refinances. Philadelphia-area title companies order here often.",
    neighbors: ["salem", "camden", "atlantic", "cumberland"] },
  { slug: "hudson", name: "Hudson", seat: "Jersey City", region: "North Jersey",
    towns: ["Jersey City", "Hoboken", "Bayonne", "Union City", "North Bergen", "West New York", "Kearny", "Secaucus", "Weehawken", "Harrison", "Guttenberg", "East Newark"],
    note: "Hudson County signings are mostly condos and high-rises in Jersey City, Hoboken and the Gold Coast. Agents allow extra time for building access and street parking, and evening appointments suit the many signers who work in Manhattan.",
    neighbors: ["bergen", "essex", "union"] },
  { slug: "hunterdon", name: "Hunterdon", seat: "Flemington", region: "Central Jersey",
    towns: ["Flemington", "Clinton", "Readington", "Raritan Township", "Lebanon", "Tewksbury", "Lambertville", "Frenchtown", "High Bridge", "Union Township", "Bethlehem Township", "East Amwell"],
    note: "Hunterdon County is rural, with estate homes and farms spread across long country roads. We schedule ahead, confirm directions with the signer, and quote travel past 20 miles before the appointment.",
    neighbors: ["warren", "morris", "somerset", "mercer"] },
  { slug: "mercer", name: "Mercer", seat: "Trenton", region: "Central Jersey",
    towns: ["Trenton", "Princeton", "Hamilton", "Ewing", "Lawrence", "West Windsor", "Robbinsville", "Hopewell", "East Windsor", "Hightstown", "Pennington"],
    note: "Trenton is the state capital and Princeton draws students, faculty and families from around the world. That means state paperwork, international documents that need remote notarization, and a busy residential market in Hamilton and West Windsor.",
    neighbors: ["hunterdon", "somerset", "middlesex", "monmouth", "burlington"] },
  { slug: "middlesex", name: "Middlesex", seat: "New Brunswick", region: "Central Jersey",
    towns: ["Edison", "Woodbridge", "New Brunswick", "Piscataway", "Old Bridge", "East Brunswick", "Perth Amboy", "Sayreville", "North Brunswick", "South Brunswick", "Monroe Township", "Metuchen"],
    note: "Middlesex County is the center of our coverage. Same-day signings are usually available in Edison, Woodbridge, New Brunswick and the Brunswicks, along with hospital and senior-community visits in Monroe Township.",
    neighbors: ["union", "somerset", "mercer", "monmouth"] },
  { slug: "monmouth", name: "Monmouth", seat: "Freehold", region: "Central Jersey",
    towns: ["Middletown", "Freehold", "Howell", "Manalapan", "Marlboro", "Long Branch", "Red Bank", "Asbury Park", "Holmdel", "Wall", "Neptune", "Ocean Township"],
    note: "Monmouth County mixes shore towns with large suburbs. We handle purchase and refinance closings from Middletown to Wall, and estate signings for retirees in Manalapan and the Freehold area.",
    neighbors: ["middlesex", "mercer", "burlington", "ocean"] },
  { slug: "morris", name: "Morris", seat: "Morristown", region: "North Jersey",
    towns: ["Morristown", "Parsippany-Troy Hills", "Randolph", "Rockaway", "Denville", "Madison", "Mount Olive", "Roxbury", "Montville", "Florham Park", "Chatham", "Morris Township"],
    note: "Morris County has many corporate offices along I-287 and Route 10, so business documents and I-9 verifications sit alongside residential closings in Randolph, Parsippany and the Chathams.",
    neighbors: ["sussex", "passaic", "essex", "union", "somerset", "hunterdon", "warren"] },
  { slug: "ocean", name: "Ocean", seat: "Toms River", region: "Central Jersey",
    towns: ["Toms River", "Lakewood", "Brick", "Jackson", "Manchester", "Point Pleasant", "Stafford", "Barnegat", "Berkeley", "Lacey", "Little Egg Harbor", "Long Beach Island"],
    note: "Ocean County has many adult and retirement communities, so wills, powers of attorney and healthcare directives make up much of our work here, alongside fast-growing purchase activity in Lakewood and Jackson.",
    neighbors: ["monmouth", "burlington", "atlantic"] },
  { slug: "passaic", name: "Passaic", seat: "Paterson", region: "North Jersey",
    towns: ["Paterson", "Clifton", "Passaic", "Wayne", "West Milford", "Little Falls", "Totowa", "Hawthorne", "Woodland Park", "Pompton Lakes", "Haledon", "Ringwood"],
    note: "Passaic County runs from dense Paterson, Clifton and Passaic up to the lake communities of West Milford and Ringwood. We plan longer travel for the northern townships and offer evening appointments in the cities.",
    neighbors: ["sussex", "morris", "essex", "bergen"] },
  { slug: "salem", name: "Salem", seat: "Salem", region: "South Jersey",
    towns: ["Pennsville", "Carneys Point", "Salem", "Pittsgrove", "Woodstown", "Penns Grove", "Upper Pittsgrove", "Mannington", "Alloway", "Elmer"],
    note: "Salem County is rural and sits just across the Delaware Memorial Bridge, so Delaware title companies often need New Jersey signers here. Booking a day ahead helps us match the closest agent.",
    neighbors: ["gloucester", "cumberland"] },
  { slug: "somerset", name: "Somerset", seat: "Somerville", region: "Central Jersey",
    towns: ["Franklin Township", "Bridgewater", "Hillsborough", "Somerville", "Basking Ridge (Bernards)", "Bound Brook", "Branchburg", "Montgomery", "North Plainfield", "Warren", "Raritan", "Manville"],
    note: "Somerset County is close to our home base, with same-day availability in Bridgewater, Somerville and Franklin. Corporate campuses in Basking Ridge and Warren also bring business and employment documents.",
    neighbors: ["hunterdon", "morris", "union", "middlesex", "mercer"] },
  { slug: "sussex", name: "Sussex", seat: "Newton", region: "North Jersey",
    towns: ["Newton", "Vernon", "Hopatcong", "Sparta", "Hardyston", "Byram", "Franklin", "Wantage", "Hamburg", "Stanhope", "Andover", "Frankford"],
    note: "Sussex County is lake and mountain country, with homes around Lake Hopatcong and in Vernon and Sparta. Distances are long, so we book ahead and quote travel past 20 miles up front.",
    neighbors: ["warren", "morris", "passaic"] },
  { slug: "union", name: "Union", seat: "Elizabeth", region: "North Jersey",
    towns: ["Elizabeth", "Union", "Plainfield", "Linden", "Westfield", "Cranford", "Summit", "Rahway", "Scotch Plains", "Hillside", "Roselle", "Springfield"],
    note: "Union County sits between our central base and North Jersey, so same-day coverage is common in Westfield, Cranford, Summit and Elizabeth. We handle residential closings, estate signings and hospital visits across the county.",
    neighbors: ["essex", "morris", "somerset", "middlesex", "hudson"] },
  { slug: "warren", name: "Warren", seat: "Belvidere", region: "North Jersey",
    towns: ["Phillipsburg", "Hackettstown", "Washington", "Belvidere", "Lopatcong", "Mansfield", "Independence", "Blairstown", "Greenwich", "Pohatcong"],
    note: "Warren County borders Pennsylvania's Lehigh Valley, and many Easton and Allentown title companies need New Jersey signers in Phillipsburg and nearby townships. We schedule ahead for the rural northern towns.",
    neighbors: ["sussex", "morris", "hunterdon"] },
];

const SERVICES = [
  { slug: "loan-signing-agent", code: "LOAN SIGNINGS", name: "Loan Signing Agents", short: "Loan signing agent",
    title: "Loan Signing Agent in New Jersey | Mobile Closings",
    description: "Certified loan signing agents for purchase, refinance, HELOC and reverse mortgage closings across New Jersey. Evening and weekend signings, scanbacks tracked.",
    h1: "Loan signing agents across New Jersey",
    lede: "MCC Solutions sends certified, background-screened signing agents to borrowers' homes, offices and anywhere else they need to sign. Title companies, lenders and attorneys get one desk that confirms the agent, tracks the documents and sends the return tracking number.",
    included: ["Purchase (buyer and seller), refinance, HELOC, reverse mortgage and loan modification packages", "Printing of e-docs, letter and legal, with a second borrower set on request", "A full page check at the table for signatures, initials and dates", "Scanbacks reviewed by the desk before the package ships", "Drop-off with your prepaid FedEx or UPS label and the tracking number sent to you"],
    who: ["Title and escrow companies, in New Jersey and out of state", "Lenders and mortgage brokers", "Real estate attorneys", "Signing services that need New Jersey coverage"],
    faqs: [
      ["How quickly can you assign a signing agent?", "During desk hours we confirm most orders within 15 minutes. Same-day signings are often possible in central and North Jersey; 24 hours of notice gives the best agent match statewide."],
      ["Do your agents print the documents?", "Yes. Agents print e-docs on dual-tray laser printers. Tell us if the borrower needs a second set."],
      ["Can the signing agent explain the loan terms?", "No. Signing agents cannot give legal or financial advice. Questions about the loan go to the lender or closing attorney, and the agent can help the borrower reach them during the signing."],
    ] },
  { slug: "mobile-notary", code: "GENERAL NOTARY", name: "Mobile Notary", short: "Mobile notary",
    title: "Mobile Notary in New Jersey | We Come to You",
    description: "A New Jersey mobile notary at your home, office, hospital or job site. Affidavits, powers of attorney, vehicle titles and business documents. Book online.",
    h1: "A mobile notary that comes to you, anywhere in New Jersey",
    lede: "Skip the trip to the bank. A commissioned New Jersey notary meets you at home, at work or at a care facility, checks your ID and notarizes your documents on the spot. The travel and service fee is quoted before we confirm.",
    included: ["Acknowledgments, jurats, oaths and affirmations", "Affidavits, powers of attorney, consent forms and vehicle titles", "Business documents, contracts and I-9 verifications", "Evening, weekend and same-day visits on request", "New Jersey's notarial fee of $2.50 per act, shown separately from travel"],
    who: ["Individuals and families", "Small businesses and HR teams", "Attorneys and their clients", "Car dealers and property managers"],
    faqs: [
      ["What do I need to bring?", "An unexpired government photo ID for every signer, and the documents unsigned. Signers sign in front of the notary."],
      ["How much does a mobile notary cost in New Jersey?", "New Jersey sets the notarial fee at $2.50 per act. The travel and service fee depends on distance and timing, and we quote it before confirming."],
      ["Can you prepare or fill out my documents?", "No. Notaries cannot draft documents or give legal advice. Bring completed documents, or have your attorney prepare them."],
    ] },
  { slug: "hospital-notary", code: "FACILITY", name: "Hospital & Care Facility Notary", short: "Hospital notary",
    title: "Hospital & Nursing Home Notary in New Jersey",
    description: "Mobile notary visits to New Jersey hospitals, nursing homes, rehab centers and hospice for powers of attorney, healthcare proxies and advance directives.",
    h1: "Hospital, nursing home and hospice notary visits in New Jersey",
    lede: "When a family member can't leave the bed, we bring the notary to them. MCC Solutions sends notaries to hospitals, rehab centers, assisted living, nursing homes and hospice care, including evenings and weekends.",
    included: ["Powers of attorney, healthcare proxies and advance directives", "Wills and estate documents, with witnesses arranged on request", "Coordination with social workers and case managers on visiting rules", "Evening, weekend and urgent same-day visits"],
    who: ["Families of patients and residents", "Hospital social workers and discharge planners", "Elder law and estate attorneys", "Assisted living and nursing home staff"],
    faqs: [
      ["What does the signer need?", "A current government photo ID and the ability to understand and willingly sign. If the signer has no ID, call the desk before booking so we can check your options."],
      ["Can the notary refuse to notarize?", "Yes. If the signer seems confused, heavily medicated or pressured, the notary must decline. A trip fee may still apply."],
      ["Can hospital staff act as witnesses?", "Many facilities don't allow staff to witness. Tell us if you need witnesses and we will bring them."],
    ] },
  { slug: "estate-planning-notary", code: "ESTATE", name: "Estate Planning Signings", short: "Wills & POA notary",
    title: "Wills, POA & Estate Signing Notary in New Jersey",
    description: "Mobile notary and witnesses for wills, powers of attorney, healthcare directives and trusts across New Jersey. At home, in the office or at a facility.",
    h1: "Notary and witnesses for wills, powers of attorney and trusts",
    lede: "Estate signings need the right people in the room. We bring a commissioned notary and, when needed, two witnesses to your client's home, office or care facility so the plan is signed correctly the first time.",
    included: ["Wills with witnesses and a notarized self-proving affidavit", "Durable and financial powers of attorney", "Healthcare proxies and advance directives", "Trust documents and deeds prepared by your attorney", "Visits at homes, offices, hospitals and senior communities"],
    who: ["Estate planning and elder law attorneys", "Families coordinating a parent's paperwork", "Financial advisors and trust officers"],
    faqs: [
      ["Do you provide witnesses?", "Yes, on request. Wills usually need two witnesses who are not beneficiaries. Let us know when you book."],
      ["Can you draft a will or power of attorney?", "No. Documents must be prepared by the signer or their attorney. We handle the signing, notarization and witnesses."],
    ] },
  { slug: "remote-online-notarization", code: "RON", name: "Remote Online Notarization (RON)", short: "Remote online notary",
    title: "Remote Online Notarization (RON) in New Jersey",
    description: "Notarize documents online over secure video with a New Jersey notary. ID verification, electronic seal and a recorded session. Book a RON session.",
    h1: "Remote Online Notarization with a New Jersey notary",
    lede: "Sign and notarize from anywhere over secure two-way video. The signer's identity is verified online, documents are signed electronically, and the notary applies an electronic seal. The session is recorded and kept as the law requires.",
    included: ["ID scan and identity questions before the session", "Electronic signatures and a tamper-evident electronic seal", "A recorded session, retained as the law requires", "Signers out of state and, for many documents, outside the U.S."],
    who: ["Signers who can't meet in person", "Expats, military families and travelers", "Title companies and lenders that accept RON closings", "Businesses with signers in several states"],
    faqs: [
      ["What do I need for a RON session?", "An unexpired government photo ID, a computer or tablet with a camera and microphone, and a stable internet connection."],
      ["Will my lender or the receiving party accept it?", "Most do, but acceptance depends on the lender, title underwriter or agency. We confirm before scheduling."],
    ] },
  { slug: "remote-ink-signed-notarization", code: "RIN", name: "Remote Ink-Signed Notarization (RIN)", short: "Remote ink notarization",
    title: "Remote Ink-Signed Notarization (RIN) in New Jersey",
    description: "Sign paper documents in wet ink on live video with a New Jersey notary, then ship the originals for the notary to complete. When paper originals are required.",
    h1: "Remote Ink-Signed Notarization when you need paper originals",
    lede: "Some documents still need wet-ink signatures. With RIN, the signer signs the paper documents on live video while the notary watches, ships the originals, and the notary completes the certificate when they arrive.",
    included: ["Live video signing of paper documents", "Shipping instructions and tracking for the originals", "Notary completes and seals the paper certificate", "Eligibility check for your state and document before booking"],
    who: ["Signers whose documents require wet ink", "Out-of-state owners selling New Jersey property", "Attorneys who need paper originals"],
    faqs: [
      ["Why isn't RIN available everywhere?", "Most temporary RIN rules from 2020 and 2021 have ended, and only a few states have permanent rules. We check eligibility for each order."],
      ["How long does RIN take?", "The video signing takes about 30 minutes. The notary finishes once the originals arrive, usually one to three business days later."],
    ] },
  { slug: "apostille-services", code: "APOSTILLE", name: "Apostille Services", short: "Apostille services",
    title: "Apostille Services in New Jersey | Notarize & Apostille",
    description: "We notarize your documents and handle the New Jersey apostille request for use abroad: powers of attorney, affidavits, school and business documents.",
    h1: "Notarization and New Jersey apostilles, handled for you",
    lede: "Documents headed to another country often need an apostille, the state certificate that confirms the notary's signature. MCC Solutions notarizes your document, prepares the request to New Jersey's Division of Revenue and Enterprise Services, and gets the finished document back to you.",
    included: ["Notarization by a New Jersey notary, with original ink signatures, as the state requires", "Preparing and submitting the apostille request to the NJ Division of Revenue and Enterprise Services", "Help ordering certified vital records from the NJ Department of Health when a birth or marriage record is involved", "A heads-up when a non-English document needs a notarized English translation first", "The state fee and our service fee quoted up front, before we start"],
    who: ["People working, studying or marrying abroad", "Families completing international adoptions", "Businesses opening accounts or companies overseas", "Expats who need a New Jersey power of attorney used abroad"],
    faqs: [
      ["What is an apostille?", "A certificate from the state that confirms a notary's or public official's signature, so the document is accepted in countries that follow the Hague Apostille Convention."],
      ["Can every document get a New Jersey apostille?", "New Jersey apostilles cover documents notarized by a New Jersey notary and records signed by certain New Jersey officials. Federal documents, such as an FBI background check, go through the U.S. Department of State instead. We'll tell you which applies before you pay."],
      ["How long does it take?", "It depends on the state's processing time and shipping. We give you an estimate when you order and keep you posted until the document is back in your hands."],
    ] },
  { slug: "private-lender-signings", code: "INVESTOR LOANS", name: "Private & Investor Loan Signings", short: "Private lender signings",
    title: "Private & Investor Loan Signings in New Jersey",
    description: "Signing agents for hard money, fix-and-flip, DSCR rental and business-purpose loans across NJ. LLC and guarantor signings, evening closings, fast scanbacks.",
    h1: "Signing agents for private and investor loans in New Jersey",
    lede: "Private lenders move fast and close on tight funding deadlines. MCC Solutions sends certified signing agents for bridge, fix-and-flip, DSCR rental, construction and other business-purpose loans, with scanbacks reviewed before release.",
    included: ["Bridge, fix-and-flip, DSCR rental, construction and other business-purpose loan packages", "Entity signings: the notary verifies each signer's identity, and your package documents their authority to sign for the LLC", "Several guarantors or members signed at one visit", "Same-day and evening closings to meet funding deadlines", "Scanbacks reviewed by the desk before release; originals shipped with your label"],
    who: ["Private and hard money lenders", "Investor-focused mortgage brokers", "Attorneys closing private loans", "Title companies handling investor transactions"],
    faqs: [
      ["Can you close a borrower who lives out of state?", "Yes. If the lender accepts remote online notarization we can close by video; otherwise we arrange a signing near the borrower."],
      ["How fast can you get a signer out?", "Same-day is often possible in central and North Jersey. Send the order as early as you can and we'll confirm the agent and time."],
    ] },
  { slug: "usps-form-1583", code: "FORM 1583", name: "USPS Form 1583 Notarization", short: "Form 1583 notarization",
    title: "Notarize USPS Form 1583 in NJ | Online or In Person",
    description: "Get USPS Form 1583 notarized for your virtual mailbox: online by video or with a mobile notary in New Jersey. Bring two IDs; done in minutes.",
    h1: "Get your USPS Form 1583 notarized, online or in person",
    lede: "Opening a virtual mailbox usually means USPS Form 1583, the authorization for an agent to receive your mail, and many mailbox providers require it notarized. MCC Solutions notarizes it by secure video from anywhere, or sends a mobile notary to you in New Jersey.",
    included: ["Remote online notarization from anywhere, usually in minutes", "Mobile notary visits in New Jersey, including evenings", "A quick check that your form is complete before you sign", "A notarized copy ready to upload to your mailbox provider", "Business accounts for virtual office and mailbox providers that refer customers"],
    who: ["Virtual mailbox customers", "New LLC owners and remote businesses", "Travelers, RVers and expats", "Virtual office, coworking and mailbox providers"],
    faqs: [
      ["What ID do I need?", "Form 1583 asks for two forms of identification, one with a photo. Have both ready, along with the completed form, unsigned."],
      ["Does my mailbox provider require notarization?", "Many do, but some verify your ID themselves. Check your provider's instructions before booking."],
      ["Who signs for a business?", "An authorized officer of the business signs the form for the company, and each person receiving mail at the address may need their own form. Your provider will tell you what they need."],
    ] },
  { slug: "child-travel-consent", code: "TRAVEL", name: "Child Travel Consent Notarization", short: "Child travel consent",
    title: "Notarized Child Travel Consent Letters in New Jersey",
    description: "Notarize a minor travel consent letter when a child travels abroad with one parent, relatives or a school group. Mobile and online options in New Jersey.",
    h1: "Notarized travel consent letters for children traveling abroad",
    lede: "When a child travels internationally without both parents, a signed and notarized consent letter from the parent who isn't traveling can prevent problems at the border or the airport. MCC Solutions notarizes it at your home or office, or online if a parent is away.",
    included: ["Notarization of the consent letter signed by the parent or parents who aren't traveling", "Remote online notarization when a parent is out of town or overseas", "An apostille arranged when the destination country asks for one", "Evening and weekend appointments before trips"],
    who: ["A parent traveling alone with children", "Grandparents and other relatives", "School, sports and church groups", "Divorced or separated parents"],
    faqs: [
      ["Is a consent letter required?", "U.S. Customs and Border Protection recommends one when a child travels without both parents, and some countries and airlines require a notarized letter. Check your destination and airline before you go."],
      ["Can you write the letter for me?", "Notaries can't draft documents. Bring your completed letter, unsigned, and every signing parent's photo ID."],
    ] },
  { slug: "document-courier", code: "COURIER", name: "Document Courier", short: "Document courier",
    title: "Document Courier for Closings in New Jersey | MCC Solutions",
    description: "Same-day pickup and delivery of closing packages and original documents for NJ title companies, law firms and lenders. Add it to any signing.",
    h1: "Same-day document courier for closings and law firms",
    lede: "Original documents have to get where they're going, fast and intact. MCC Solutions picks up and delivers closing packages, signed originals and legal documents across New Jersey, on its own or added to a signing.",
    included: ["Pickup and drop-off of closing packages and signed originals", "Add it to any signing at checkout, or order a run on its own", "Proof of delivery: who received it and when", "Runs within 20 miles at a flat rate; longer runs quoted up front", "Evening and same-day runs when a deadline won't wait"],
    who: ["Title and escrow companies", "Real estate and estate planning attorneys", "Lenders and mortgage brokers", "Hospitals and families moving documents between offices"],
    faqs: [
      ["Can you pick up documents after a signing?", "Yes. Add the courier at checkout and the notary or a courier delivers the signed originals to your office instead of shipping them."],
      ["How is it priced?", "A flat rate for runs within 20 miles, shown at checkout. Longer runs are quoted before we confirm."],
    ] },
  { slug: "print-and-scan", code: "PRINT · SCAN", name: "Mobile Printing & Scanbacks", short: "Printing & scanbacks",
    title: "Mobile Document Printing & Scanbacks in New Jersey",
    description: "Your notary prints the documents, the signer signs, and signed pages come back scanned the same day. Add printing and scanbacks to any NJ signing.",
    h1: "We print it, you sign it, we scan it back",
    lede: "Signers often can't print a 150-page package, and your team needs the signed pages before the originals arrive. Add printing and scanbacks to any signing and MCC Solutions handles both.",
    included: ["Printing on dual-tray laser printers, letter and legal", "A second set for the borrower on request", "Signed pages scanned and sent the same day", "Scanbacks reviewed by the desk for missed signatures before release", "Secure delivery through your client portal, never by open email attachment"],
    who: ["Title and escrow companies", "Lenders that send e-docs", "Attorneys and their clients", "Individuals without a printer at home"],
    faqs: [
      ["How many pages can you print?", "The standard add-on covers packages up to 150 pages. Larger packages are quoted when you book."],
      ["How do I get the scanbacks?", "They're uploaded to your client portal once the desk checks them, and you get an email when they're ready."],
    ] },
  { slug: "witness-services", code: "WITNESS", name: "Witness Services", short: "Witnesses",
    title: "Witnesses for Signings in New Jersey | Wills, Deeds, RON",
    description: "Need witnesses for a will, deed or remote online notarization? MCC Solutions brings independent witnesses to your NJ signing. Book per witness.",
    h1: "Independent witnesses for wills, deeds and remote signings",
    lede: "Some documents need witnesses who aren't related to the signer or named in the document. MCC Solutions brings one or two independent witnesses to the signing, at home, in a hospital or by video for remote sessions.",
    included: ["One or two independent adult witnesses per signing", "Witnesses for wills, codicils, deeds and other documents that require them", "Witnesses on video for remote online notarization sessions", "Booked per witness at checkout"],
    who: ["Families signing wills and estate documents", "Estate planning and elder law attorneys", "Hospitals and care facilities that don't allow staff to witness", "Title companies with documents that need witnessing"],
    faqs: [
      ["Who can be a witness?", "Usually an adult who isn't related to the signer and isn't named in the document. Requirements vary by document, so check with your attorney if you're unsure."],
      ["Do witnesses need ID?", "Our witnesses bring photo ID, and their names and contact details can be recorded on the document if it asks for them."],
    ] },
  { slug: "passport-consent-form", code: "PASSPORT", name: "Passport Consent Form (DS-3053)", short: "Passport consent",
    title: "Notarize Passport Form DS-3053 in New Jersey",
    description: "When a parent can't attend a child's passport appointment, Form DS-3053 must be notarized. Mobile or online notary in NJ, with an ID copy for the application.",
    h1: "Get passport Form DS-3053 notarized, at home or online",
    lede: "When one parent or guardian can't come to a child's passport appointment, the U.S. State Department requires a notarized Statement of Consent, Form DS-3053. MCC Solutions notarizes it at your home or office, or online if you're away.",
    included: ["Notarization of Form DS-3053 for the parent or guardian who can't attend", "A copy of the ID you show the notary, which the application requires", "Remote online notarization if you're out of town", "Evening and weekend appointments before passport dates"],
    who: ["Parents who can't attend their child's passport appointment", "Military and traveling parents", "Separated or divorced parents", "Grandparents and guardians"],
    faqs: [
      ["How soon do I need to use it?", "The State Department asks that the form be submitted within 90 days after it's signed and notarized, so book close to the passport appointment."],
      ["What do I bring?", "The completed form, unsigned, and your government photo ID. We'll give you a copy of the ID for the application."],
      ["I'm overseas. Can I still use you?", "Often, through remote online notarization. Some countries require you to use a U.S. embassy or consulate instead, so check the State Department's instructions for where you are."],
    ] },
  { slug: "process-serving", requestType: "process_serve", code: "PROCESS SERVING", name: "Process Serving", short: "Process serving",
    title: "Process Server in New Jersey | Court Papers Served Fast",
    description: "Process serving across New Jersey for attorneys, landlords and individuals. Every attempt logged with date, time and notes, plus a signed affidavit of service.",
    h1: "Process serving across New Jersey, with every attempt on record",
    lede: "MCC Solutions serves summonses, complaints, subpoenas and other court papers throughout New Jersey. Every attempt is logged with the date, time and result, and you get a signed affidavit of service when it's done.",
    included: ["Personal and substitute service as the court rules allow", "Every attempt logged: date, time, place and result", "Signed affidavit of service, uploaded for you", "Standard, rush and same-day options", "Status updates from the desk, with no chasing needed"],
    who: ["Law firms and solo attorneys", "Landlords and property managers", "Collection agencies", "Individuals with a case in New Jersey courts"],
    faqs: [
      ["Who can serve papers in New Jersey?", "New Jersey court rules allow service by the sheriff or by a competent adult who isn't a party to the case. Our servers are background-checked adults who aren't involved in your matter."],
      ["What if the person can't be found?", "We make repeat attempts at different times and log each one. If service isn't possible, you get the attempt log and an affidavit of non-service for your next step."],
      ["How do I send the papers?", "Attach them to the request form above (PDF or photos). Firms with an account can upload them in the client portal. We can also pick up originals."],
    ] },
  { slug: "document-recording", requestType: "recording", code: "RECORDING", name: "Document Recording", short: "Document recording",
    title: "Document Recording Service in New Jersey | Deeds & Mortgages",
    description: "We record deeds, mortgages, releases and other documents with New Jersey county clerks, electronically or in person, and send you the recorded copy.",
    h1: "Deeds, mortgages and releases recorded with the county",
    lede: "Once the signing is done, the documents still have to be recorded. MCC Solutions submits deeds, mortgages, releases, assignments and other documents to New Jersey county clerks, electronically where the county accepts it, and sends you the recorded copy.",
    included: ["Review for obvious recording problems before submission (missing pages, signatures or notary blocks)", "Electronic recording where the county accepts it, or in-person filing", "County recording fees passed through at cost", "The recorded copy with book and page, or instrument number, sent to you"],
    who: ["Small title agencies", "Real estate and estate attorneys", "Private lenders and investors", "Individuals transferring property"],
    faqs: [
      ["Do you check the documents?", "We check that pages, signatures and notary certificates are present before submitting. We don't give legal advice on the content of the document."],
      ["How are fees charged?", "Our service fee plus the county's recording fees at cost, quoted before we file."],
    ] },
  { slug: "embassy-legalization", requestType: "legalization", code: "LEGALIZATION", name: "Embassy Legalization", short: "Embassy legalization",
    title: "Embassy Legalization of Documents | New Jersey | MCC",
    description: "Documents going to a country that doesn't accept apostilles? We coordinate notarization, state or federal authentication, and embassy legalization.",
    h1: "Embassy legalization for countries that don't accept apostilles",
    lede: "Some countries don't take apostilles and require embassy or consular legalization instead. MCC Solutions coordinates the full chain (notarization, state or federal authentication, and the embassy step) through our legalization partners, and keeps you updated until the documents are back.",
    included: ["A check of what your destination country requires", "Notarization by a New Jersey notary when needed", "Authentication and embassy submission through our partners", "Government and embassy fees passed through at cost", "Updates at each step until the documents are returned"],
    who: ["Businesses working with partners abroad", "People relocating, marrying or working overseas", "Attorneys handling international matters"],
    faqs: [
      ["How do I know if I need an apostille or legalization?", "It depends on the destination country. Tell us where the documents are going and we'll confirm which process applies before you pay."],
      ["How long does it take?", "Embassy timelines vary widely by country. We give you an estimate when we quote the request."],
    ] },
  { slug: "certified-translation", requestType: "translation", code: "TRANSLATION", name: "Certified Translation", short: "Certified translation",
    title: "Certified Translation with Notarization in New Jersey",
    description: "Certified translations from professional translation partners, notarized when your court, agency or apostille requires it. Request a quote online.",
    h1: "Certified translations, notarized when it's required",
    lede: "Courts, agencies and foreign governments often require a certified translation, and sometimes a notarized one. MCC Solutions works with professional translators for the translation and handles the notarization, so you have one point of contact.",
    included: ["Translation by professional translation partners", "A translator's certificate of accuracy", "Notarization of the translator's statement when required", "Apostille or legalization arranged when the documents go abroad"],
    who: ["Immigration and family law attorneys", "People submitting foreign records to courts or agencies", "Businesses with foreign-language contracts"],
    faqs: [
      ["Which languages?", "Most major languages through our partners. Tell us the languages and page count and we'll quote it."],
      ["Do you give immigration advice?", "No. We provide translations and notarization only. Talk to an attorney or accredited representative about immigration questions."],
    ] },
  { slug: "document-shredding", requestType: "shredding", code: "SHREDDING", name: "Secure Document Shredding", short: "Document shredding",
    title: "Secure Document Shredding Pickup in New Jersey | MCC",
    description: "Pickup and certified destruction of closing files, legal records and estate paperwork through our shredding partners. Certificate of destruction available.",
    h1: "Secure shredding for closing files, legal records and estates",
    lede: "Old closing files, client records and estate paperwork hold exactly the personal information you're required to protect. MCC Solutions arranges pickup and secure destruction through certified shredding partners, with a certificate of destruction for your records.",
    included: ["Pickup from your office or the estate", "Destruction through certified shredding partners", "A certificate of destruction on request", "One-time cleanouts or scheduled pickups"],
    who: ["Title agencies and law firms clearing retention backlogs", "Executors and families settling an estate", "Small businesses and medical offices"],
    faqs: [
      ["Do I get proof it was destroyed?", "Yes. Ask for a certificate of destruction and we'll send it after the job."],
      ["How is it priced?", "By volume (boxes or bags) and pickup location, quoted before we schedule."],
    ] },
  { slug: "estate-document-scanning", requestType: "estate_scan", code: "ESTATE SCANNING", name: "Estate Document Scanning", short: "Estate scanning",
    title: "Estate Document Scanning & Organizing in New Jersey",
    description: "We pick up an estate's paperwork, scan it, and organize it into clearly named files for the executor or attorney. Originals returned or securely shredded.",
    h1: "Estate paperwork scanned, organized and ready for the executor",
    lede: "Settling an estate means going through boxes of statements, deeds, policies and letters. MCC Solutions picks up the paperwork, scans it, and organizes it into clearly named files so the executor and attorney can find what they need.",
    included: ["Pickup of the paperwork from the home or office", "Scanning to searchable PDF files", "Files organized and named by type and date", "Originals returned, or securely shredded on request", "Notarization of estate documents while we're there"],
    who: ["Executors and family members", "Estate and elder law attorneys", "Funeral homes helping families"],
    faqs: [
      ["Is my family's information kept private?", "Yes. Scans are delivered securely, our team signs confidentiality agreements, and originals are returned or shredded as you choose."],
    ] },
  { slug: "lien-waiver-collection", requestType: "lien_waivers", code: "LIEN WAIVERS", name: "Lien Waiver Collection", short: "Lien waivers",
    title: "Notarized Lien Waiver Collection in New Jersey | MCC",
    description: "We collect signed, notarized lien waivers from subcontractors and suppliers on your draw schedule, on site or at their offices, and send them back the same day.",
    h1: "Notarized lien waivers collected on your draw schedule",
    lede: "Draws stall when one subcontractor's notarized waiver is missing. MCC Solutions sends a notary to your job site or to each subcontractor and supplier, collects signed, notarized lien waivers, and returns them to you the same day.",
    included: ["On-site collection at the project, or visits to each subcontractor", "Notarization of every waiver", "Scans sent the same day; originals by courier or mail", "Recurring scheduling for monthly draws"],
    who: ["General contractors", "Construction lenders and draw administrators", "Developers and owners"],
    faqs: [
      ["Do you prepare the waivers?", "No. Send us the forms you use; we handle the signing and notarization."],
    ] },
  { slug: "property-inspections", requestType: "inspection", code: "INSPECTIONS", name: "Property Inspections", short: "Property inspections",
    title: "Occupancy & Photo Property Inspections in New Jersey",
    description: "Occupancy checks and exterior or interior photo inspections across New Jersey for lenders, servicers, investors and attorneys. Time-stamped photos and notes.",
    h1: "Occupancy checks and photo inspections across New Jersey",
    lede: "Need eyes on a property? MCC Solutions sends a field representative to confirm occupancy and condition, with time-stamped photos and notes delivered to you. These are visual inspections, not licensed home inspections or appraisals.",
    included: ["Occupancy checks", "Exterior photo inspections", "Interior photos when access is arranged", "Time-stamped photos and a short written report"],
    who: ["Lenders and loan servicers", "Real estate investors", "Attorneys and property managers"],
    faqs: [
      ["Is this a home inspection?", "No. It's a visual occupancy and condition check with photos. For structural or systems inspections, hire a licensed home inspector."],
    ] },
  { slug: "court-filing", requestType: "court_filing", code: "COURT RUNS", name: "Court Filing & Document Runs", short: "Court filing",
    title: "Court Filing & Courthouse Runs in New Jersey | MCC",
    description: "Papers filed in person at New Jersey courthouses, documents picked up and delivered, and copies pulled from court files. Same-day runs available.",
    h1: "Court filings and courthouse runs, handled the same day",
    lede: "Some filings still have to be walked in, some originals have to be hand-delivered, and some copies only come from the clerk's counter. MCC Solutions sends a runner to New Jersey courthouses and county offices so your staff doesn't lose half a day.",
    included: ["In-person filing at the clerk's office, with the stamped copy back to you", "Pickup and hand delivery of originals between offices and courts", "Copies pulled from court files and sent as scans the same day", "Court and copy fees passed through at cost", "Pairs with process serving: serve, file the affidavit, done"],
    who: ["Law firms and solo attorneys", "Paralegals juggling deadlines", "Title agencies and lenders", "Self-represented people who need a hand-delivery"],
    faqs: [
      ["Do you e-file for us?", "No. Attorneys file through the court's own electronic system. We handle what has to be done in person: walk-in filings, deliveries and copies."],
      ["Can you tell me what to file?", "No. We're not lawyers and can't advise on what to file or how. Tell us exactly what to file and where, and we'll take care of the trip."],
      ["How fast is a run?", "Same-day runs are usually possible when the request comes in by late morning. Rush handling is available."],
    ] },
  { slug: "records-retrieval", requestType: "records_retrieval", code: "RECORDS", name: "Records Retrieval", short: "Records retrieval",
    title: "Records Retrieval in New Jersey | Deeds, Court & Vital Records",
    description: "We pull copies of recorded deeds and mortgages, court records, business filings and vital records from New Jersey counties and agencies, certified when you need it.",
    h1: "Deeds, court files and certified records, pulled for you",
    lede: "Estates, closings and lawsuits all stall on a missing record. MCC Solutions retrieves copies of recorded documents, court records, business filings and vital records from New Jersey county offices and agencies, certified when you need it, and sends them back to you.",
    included: ["Recorded documents: deeds, mortgages, releases and liens", "Court records from the county courthouse", "Business and corporate filings", "Vital records where you're eligible to request them", "Agency and certification fees passed through at cost"],
    who: ["Estate and elder law attorneys", "Title agencies and abstractors", "Executors and families settling an estate", "Litigation teams"],
    faqs: [
      ["Can anyone get a birth or death certificate?", "No. New Jersey limits certified vital records to eligible people, such as family members or legal representatives. We'll tell you what proof of eligibility the office needs before we go."],
      ["Do you do title searches?", "No. We retrieve specific records you ask for. A full title search should come from a licensed title agency or abstractor."],
      ["How do I know what to ask for?", "Give us names, the property address, a book and page, or a docket number. The more you give us, the faster we find it."],
    ] },
  { slug: "skip-tracing", requestType: "skip_trace", code: "SKIP TRACE", name: "Skip Tracing", short: "Skip tracing",
    title: "Skip Tracing for Process Serving & Collections | New Jersey",
    description: "Can't find the person you need to serve? We run database searches for a current address for permissible purposes like service of process and judgment collection.",
    h1: "A current address for the person you can't find",
    lede: "When the address on file is old, service stalls. MCC Solutions runs database searches to find a likely current address for the person you need to serve or reach, then our servers can go straight there.",
    included: ["Database search for current and past addresses", "Results in plain language, with how recent each address is", "Straight handoff to a process server when you're ready", "Searches only for permissible legal purposes"],
    who: ["Law firms that need to serve someone who moved", "Collection agencies and judgment creditors", "Estate attorneys looking for heirs", "Landlords with a former tenant to serve"],
    faqs: [
      ["Is this a private investigation?", "No. It's a database search for a current address. We don't do surveillance or investigations, which require a New Jersey private detective license."],
      ["Is the address guaranteed?", "No. Database records can be out of date. We tell you how recent each result is, and an attempt at the address confirms it."],
      ["What purposes do you accept?", "Legitimate legal purposes such as service of process, collecting a judgment or debt, and finding heirs. We don't search for anyone trying to locate a person for personal reasons."],
    ] },
  { slug: "medical-records-retrieval", requestType: "medical_records", code: "MEDICAL RECORDS", name: "Medical Records Pickup", short: "Medical records",
    title: "Medical Records Pickup & Delivery in New Jersey | MCC",
    description: "We request and pick up medical records from New Jersey hospitals and practices with a signed patient authorization or subpoena, and deliver them to you.",
    h1: "Medical records picked up and delivered, with the paperwork right",
    lede: "Personal injury, disability and estate matters all need medical records, and providers move faster when someone shows up with the right paperwork. MCC Solutions delivers the request, follows up, picks up the records and brings them back to you.",
    included: ["Delivery of the request with the signed authorization or subpoena", "Follow-up with the records department until they're ready", "Pickup and secure delivery to your office", "A notary visit to get the patient's authorization signed, if you need it", "Provider copy fees passed through at cost"],
    who: ["Personal injury and workers' comp attorneys", "Disability claim representatives", "Estate attorneys and executors", "Patients collecting their own records"],
    faqs: [
      ["Can you get records without the patient's permission?", "No. Providers release records with a valid signed authorization from the patient or their legal representative, or a subpoena. We help get the authorization signed if needed."],
      ["How long does it take?", "It depends on the provider's records department. We follow up until the records are ready and tell you as soon as they're picked up."],
    ] },
  { slug: "i9-verification", requestType: "i9_verification", code: "FORM I-9", name: "I-9 Authorized Representative", short: "I-9 verification",
    title: "I-9 Authorized Representative in New Jersey | Remote Hires",
    description: "Hiring a remote employee in New Jersey? Our representative meets them, examines their original documents in person and completes Section 2 of Form I-9 for you.",
    h1: "I-9 verification for your New Jersey remote hires",
    lede: "Form I-9 needs someone to physically examine a new hire's original documents. When your new employee is in New Jersey and you aren't, MCC Solutions sends a representative to meet them and complete Section 2 on your behalf.",
    included: ["A visit at the employee's home, a coffee shop or an office", "In-person examination of the employee's original documents", "Section 2 completed and signed as your authorized representative", "The completed form and copies, if you want them, sent back the same day"],
    who: ["Remote-first companies hiring in New Jersey", "Staffing agencies and PEOs", "HR teams without a local office"],
    faqs: [
      ["Is this a notarization?", "No. Form I-9 isn't notarized. Your company names us as its authorized representative to examine documents and complete Section 2. You remain responsible for the form."],
      ["Which documents should the employee bring?", "Original, unexpired documents from the Lists of Acceptable Documents on Form I-9. The employee chooses which ones to present."],
      ["Can you use E-Verify for us?", "No. If your company uses E-Verify, you create the case yourself from the completed form."],
    ] },
  { slug: "jail-and-prison-notary", requestType: "jail_notary", code: "FACILITY VISITS", name: "Jail & Correctional Facility Notary", short: "Jail and prison notary",
    title: "Jail & Prison Notary in New Jersey | Facility Visits",
    description: "Need a document notarized for someone in a New Jersey jail, prison or detention center? We coordinate the visit with the facility and notarize on site.",
    h1: "Notary visits to jails, prisons and detention centers in New Jersey",
    lede: "A power of attorney, an affidavit or a consent form still needs a notary when the signer is incarcerated. We work with the facility to arrange the visit, check the signer's identity and notarize on site. Facilities set their own rules, so we start by asking what yours requires.",
    included: ["Contacting the facility to learn its visiting and legal-visit procedures", "Identity checks that meet notary requirements, including help when the signer has no standard ID", "Notarization of acknowledgments and jurats at the facility, where the facility allows it", "Return of the notarized documents to you the way you choose"],
    who: ["Attorneys and legal staff", "Families arranging a power of attorney or childcare consent", "Bail bond and court-support offices", "Signers' employers, banks and landlords"],
    faqs: [
      ["Will the facility allow a notary visit?", "That is up to the facility. Each one has its own rules about who can visit, when, and what you can bring in. We ask first and tell you what they say before we book. We can't promise access."],
      ["Does the person need ID?", "A notary has to be satisfied of the signer's identity. A facility-issued ID may or may not be accepted for a given document. Tell us what the signer has and we'll say what we can do. If we can't confirm identity, we can't notarize."],
      ["Can you tell us what to put in the document?", "No. We notarize signatures. For what the document should say, ask the attorney or the office that requested it."],
      ["Do you charge extra for facility visits?", "Facility visits take extra time for security and waiting, so the fee is quoted for the visit, not the standard rate. We confirm it before we go."],
    ] },
  { slug: "estate-planning-signing-package", requestType: "estate_package", code: "ESTATE SIGNINGS", name: "Estate Planning Signing Package", short: "Estate planning signing package",
    title: "Estate Planning Signing Package: Notary & Witnesses in NJ",
    description: "A notary and witnesses for wills, powers of attorney and healthcare directives, in one visit. Built for New Jersey estate attorneys and their clients.",
    h1: "Estate planning signings with a notary and witnesses, in one visit",
    lede: "Estate documents are signed once, and they need to be signed correctly. We send a commissioned New Jersey notary and, if you ask, the witnesses, so the attorney's signing meeting goes the way the attorney planned. We notarize and witness. The attorney drafts and advises.",
    included: ["A New Jersey notary at the client's home, the attorney's office or a care facility", "Witnesses on request, with their names and addresses recorded as the attorney needs", "Notarization of acknowledgments, jurats and self-proving affidavits that call for them", "Documents kept in order, with the attorney's signing instructions followed page by page"],
    who: ["Estate planning and elder law attorneys", "Clients signing at home or in a care facility", "Families arranging a power of attorney or healthcare directive on short notice"],
    faqs: [
      ["How many witnesses are needed?", "It depends on the document, and the attorney who prepared it will tell you. New Jersey wills generally need two witnesses. Tell us how many you need when you book."],
      ["Can you explain the documents?", "No. We aren't lawyers and can't give legal advice. We can tell the signer what each notarial act is, and the attorney explains the documents."],
      ["Can you come to a hospital or care facility?", "Yes. Tell us the facility and floor, and we'll arrange access with the staff."],
      ["What if one signer seems confused or pressured?", "We have to stop. A notary can't proceed if the signer seems unsure about what they are signing or why we are there, and we'll tell the attorney."],
    ] },
  { slug: "vehicle-title-notary", code: "VEHICLE TITLE", name: "Vehicle Title & MVC Paperwork Notary", short: "Vehicle title notary",
    title: "Vehicle Title & Car Sale Notary in New Jersey | Mobile",
    description: "Mobile notary for car title transfers, out-of-state titles, powers of attorney for the MVC and odometer statements. We come to you, including after a death.",
    h1: "Car titles and MVC paperwork notarized where you are",
    lede: "Selling a car to an out-of-state buyer, handling a loved one's vehicle after they pass, or giving someone power of attorney to deal with the MVC often means a notarized signature. A commissioned MCC notary meets you at home, at work or at the dealership.",
    included: ["Notarized signatures on title assignments that require them (some states' titles do)", "Powers of attorney for motor vehicle transactions", "Affidavits and statements for the MVC or an out-of-state DMV", "Visits for families handling a deceased owner's vehicle"],
    who: ["Private buyers and sellers", "Families settling an estate", "Auto dealers with out-of-state customers", "People who can't get to the MVC themselves"],
    faqs: [
      ["Does a New Jersey title need to be notarized?", "Usually not for a simple sale between people in New Jersey. Other states' titles and some MVC forms do require notarization, so check what the receiving office asks for. We can't advise on which forms you need."],
      ["Can you go to the MVC for me?", "No. We notarize and deliver documents. The MVC visit itself is up to you or the person you give power of attorney to."],
    ] },
  { slug: "business-notary", code: "BUSINESS", name: "Business & Dealer Notary Services", short: "Business notary",
    title: "Business & Auto Dealer Notary Services in New Jersey",
    description: "Mobile notary accounts for NJ auto dealers, property managers, HR teams, contractors, insurers and funeral homes. On-site visits, monthly invoicing.",
    h1: "Notary services for New Jersey businesses",
    lede: "Dealerships, property managers, HR teams and other businesses need documents notarized every week. Open a business account and MCC Solutions sends a commissioned notary to your office, lot or job site, or to your customer, and bills you once a month.",
    included: ["On-site visits at your office, dealership, job site or a customer's home", "Notarization for out-of-state buyers and customers who can't come in", "Remote online notarization for signers who are out of state or traveling", "One business account: online ordering, status updates and monthly invoices", "Standing instructions saved to your account, so every visit is done your way"],
    who: ["Auto dealers: title and registration paperwork, powers of attorney, out-of-state buyers", "Property managers and landlords: leases, affidavits, estoppel certificates", "HR and staffing teams: I-9 verifications and employment documents", "Contractors: lien waivers, contracts and affidavits", "Insurance and public adjusters: sworn proofs of loss, often at the property", "Funeral homes: affidavits and estate paperwork for families", "Banks, credit unions, accountants and financial advisors: overflow and homebound clients"],
    faqs: [
      ["How does billing work for businesses?", "Business accounts get one invoice a month for every visit, payable by ACH or card. Each line shows the notarial fee separately from the service and travel fee."],
      ["Can a notary come to our customer instead of our office?", "Yes. We send the notary wherever the signer is: home, hospital, job site or another office. You place the order; we confirm the time with the signer."],
      ["Can you prepare our documents?", "No. Notaries can't draft documents or give legal advice. Send completed documents, and we handle the signing and notarization."],
    ] },
];

module.exports = { COUNTIES, SERVICES };
