// Websites and local SEO: service pages and guides. General information. No ranking promises, no invented statistics.
// Google's guidelines and tools change; phrases like "check Google's current guidance" are deliberate. Review once a year.

const SERVICES = [
  {
    slug: "local-seo", name: "Local SEO", short: "Local SEO",
    title: "Local SEO for New Jersey Small Businesses",
    description: "Local SEO for New Jersey small businesses: Google Business Profile, service and town pages, citations and tracking. Honest work, no ranking promises.",
    intro: "Local SEO is the work that helps people near you find you when they search for what you do. We focus on the parts you can control, explain what we did in plain terms, and never promise a ranking, because no one honestly can.",
    includes: ["A review of your current site, Google Business Profile and listings", "Google Business Profile setup or cleanup", "Service pages and town pages written for real customers", "Titles, descriptions and structured data that match each page", "Consistent name, address and phone details across the web", "Search Console and analytics set up so you can see results", "A short monthly note on what changed and what is next, if you want ongoing help"],
    process: [["Audit", "We look at your site, Business Profile and listings and tell you what is missing or wrong."], ["Fix the foundation", "Accurate business details, a complete profile, a fast mobile site and correct page titles."], ["Build useful pages", "Pages for each service and area you really serve, with real details instead of filler."], ["Measure", "Search Console and analytics set up, with calls and form submissions tracked."]],
    fit: ["Service businesses with a local customer base: trades, medical and dental offices, salons, restaurants, professional firms", "Owners who rank on page two and want a clear plan", "Businesses opening a second area or service"],
    faqs: [["Can you guarantee first place on Google?", "No. No honest agency can. Google decides rankings, and results depend on competition, reviews and history. We do the work that improves your chances and show you the data."], ["How long until I see results?", "Fixing a broken profile can help within weeks. Competitive searches can take months. See our guide on how long SEO takes."], ["Do I own the accounts?", "Yes. Your Business Profile, Search Console, analytics and domain stay in your name."]],
    guides: ["what-is-local-seo", "local-seo-checklist-for-small-business", "how-long-does-seo-take"],
  },
  {
    slug: "google-business-profile", name: "Google Business Profile", short: "Business Profile",
    title: "Google Business Profile Setup & Optimization in NJ",
    description: "Google Business Profile setup, verification, cleanup and ongoing care for New Jersey small businesses, done within Google's guidelines.",
    intro: "Your Google Business Profile is often the first thing a customer sees: your hours, phone, reviews and a map pin. We set it up correctly, fix problems, and keep it accurate.",
    includes: ["Claiming and verifying your profile, or recovering access from a former owner", "The right primary and secondary categories", "Hours, services, service areas and a clear description", "Photos that show your real business", "A plan for getting genuine reviews and answering them", "Fixes for duplicate, suspended or incorrect listings"],
    process: [["Find or claim it", "We check whether a profile already exists and who controls it."], ["Verify", "Google decides how you verify: phone, email, video or another method."], ["Complete it", "Every field filled in accurately, with no keyword stuffing in the business name."], ["Maintain it", "Updated hours, new photos and review responses as the business changes."]],
    fit: ["Businesses that never set up a profile", "Owners locked out or with a duplicate listing", "Service-area businesses that work at customers' locations"],
    faqs: [["Can you get my suspended profile back?", "Often, but not always. Suspensions usually come from guideline problems. We find the cause, fix it and file the appeal. Google makes the final decision."], ["Can I hide my home address?", "Service-area businesses can hide their address in many cases. Google's rules decide, so check the current guidelines."], ["Will you write fake reviews?", "No. Fake or incentivized reviews break Google's rules and can get a profile penalized."]],
    guides: ["how-to-set-up-google-business-profile", "how-to-get-more-google-reviews", "nap-consistency-and-local-citations"],
  },
  {
    slug: "website-design", name: "Website design", short: "Website design",
    title: "Small Business Website Design in New Jersey",
    description: "Fast, mobile-first small business websites built in New Jersey, with a fixed written quote. You own the domain, hosting and content.",
    intro: "We build small, clear websites around what your customers ask first: what you do, where you work, how much it costs and how to reach you. They load fast on a phone, and you own everything.",
    includes: ["A fixed written quote before work starts", "Mobile-first design that is accessible and fast", "Contact and booking forms that work, with spam protection", "Service pages and an about page with your real details", "Titles, descriptions and structured data set up from day one", "Search Console and analytics installed", "A handoff walkthrough, with your accounts in your name"],
    process: [["Short call", "We learn what the business does and what the site must do."], ["Written quote", "A fixed price and timeline."], ["Build and review", "You review a working site and we adjust it."], ["Launch and hand-off", "We publish, test forms and tracking, and walk you through changes."]],
    fit: ["New businesses with no site", "Owners on an old site that is slow or hard to edit", "Businesses that outgrew a template page"],
    faqs: [["How much does a website cost?", "It depends on the number of pages, forms or booking, and whether you want local SEO. We give a fixed written quote after a short call. See our guide on website cost."], ["Do I own the site?", "Yes. You own the domain, hosting accounts and content."], ["Can I edit it myself?", "We can build it so you can make simple changes, or handle updates for you. We will tell you which approach fits."]],
    guides: ["how-much-does-a-small-business-website-cost", "what-every-local-business-website-needs", "own-your-domain-and-hosting"],
  },
  {
    slug: "website-speed", name: "Website speed & Core Web Vitals", short: "Speed",
    title: "Website Speed & Core Web Vitals Fixes",
    description: "Faster websites for small businesses: image and font fixes, caching, render-blocking resources and Core Web Vitals, explained in plain language.",
    intro: "A slow site loses visitors and can hurt search results. We measure what is slow, fix the causes, and show you the before and after.",
    includes: ["PageSpeed and Core Web Vitals review on mobile and desktop", "Image compression and modern formats", "Font and CSS loading fixes", "Removing or deferring scripts that slow the page", "Caching and compression on the server", "A short report with the changes made"],
    process: [["Measure", "Lab tests plus real-user data where Google has it."], ["Prioritize", "The few fixes that matter most, not a long list."], ["Fix", "Changes made and tested on mobile."], ["Recheck", "Results compared with the starting point."]],
    fit: ["Sites with poor PageSpeed or Core Web Vitals results", "Heavy template sites with large images and plug-ins", "Businesses running paid ads to a slow page"],
    faqs: [["Will a faster site rank higher?", "Speed is one of many factors and mostly helps visitors. Slow sites lose customers, which is reason enough to fix it."], ["Can you fix WordPress sites?", "Often yes. Heavy plug-ins and themes are the usual cause. We will tell you if a rebuild is the better choice."], ["What is a good score?", "Scores are a tool, not the goal. Real load time on a phone matters more. See our Core Web Vitals guide."]],
    guides: ["core-web-vitals-explained", "what-every-local-business-website-needs", "local-seo-checklist-for-small-business"],
  },
  {
    slug: "technical-seo-and-schema", name: "Technical SEO & schema markup", short: "Technical SEO",
    title: "Technical SEO & Schema Markup for Small Business Sites",
    description: "Technical SEO for small business websites: indexing, sitemaps, redirects, canonical tags and schema markup for local businesses and services.",
    intro: "Technical SEO makes sure Google can find, read and understand your pages. It is the unseen layer that keeps good content from going to waste.",
    includes: ["Indexing check in Search Console and a fix list", "XML sitemap and robots.txt review", "Redirects, canonical tags and broken links", "Local business, service, FAQ and breadcrumb schema", "Job posting schema for businesses that hire", "HTTPS and security header review"],
    process: [["Crawl and index check", "What Google sees, what it skips and why."], ["Fix errors", "Broken links, duplicate pages and bad redirects."], ["Add structured data", "Schema that matches what is visible on the page."], ["Validate", "Google's Rich Results Test and Search Console reports."]],
    fit: ["Sites with pages missing from Google", "Sites after a redesign or domain change", "Businesses that want rich results such as FAQs or job listings"],
    faqs: [["Does schema improve rankings?", "Not directly. It helps Google understand the page and can make you eligible for rich results. It must match what is visible on the page."], ["Why are my pages not indexed?", "Common causes are noindex tags, duplicate content, thin pages, blocked crawling or a new site. We check each one."], ["Do I need this for a small site?", "A basic check is worthwhile for every site. Large fixes are rarely needed on a clean small site."]],
    guides: ["schema-markup-for-local-business", "how-to-set-up-google-search-console", "title-tags-and-meta-descriptions"],
  },
  {
    slug: "website-care", name: "Website care & updates", short: "Website care",
    title: "Website Care Plans & Updates for NJ Small Businesses",
    description: "Monthly website care: updates, backups, security checks, speed and content changes for small businesses in New Jersey.",
    intro: "A website is not finished at launch. Hours change, prices change, plug-ins go out of date. Care means someone is looking after it so it keeps working.",
    includes: ["Content and price updates when your business changes", "Software, plug-in and security updates", "Backups and uptime checks", "Form and booking tests", "Monthly Search Console and analytics check", "A short monthly summary of what was done"],
    process: [["Review", "We learn how your site is built and what depends on it."], ["Set a routine", "Monthly checks with a list of what we look at."], ["Respond", "Send us a change and we handle it."], ["Report", "A plain-language note each month."]],
    fit: ["Owners who do not want to touch the site", "Businesses with a form or booking system that must always work", "Sites that fell out of date"],
    faqs: [["What does care cost?", "We quote it after seeing the site. Pricing depends on what runs on it and how often it changes."], ["Can I cancel?", "Yes. You own the site and accounts, and we hand over what you need."], ["Do you support sites you did not build?", "Often yes, after a review."]],
    guides: ["own-your-domain-and-hosting", "what-every-local-business-website-needs", "core-web-vitals-explained"],
  },
];

const GUIDES = [
  { slug: "what-is-local-seo", title: "What is local SEO? A plain-language guide", updated: "2026-10-07", services: ["local-seo"],
    description: "What local SEO is, how it differs from regular SEO, what Google looks at for local searches, and where a small business should start.",
    intro: "Local SEO is how a business shows up when someone nearby searches for what it does. Here is how it works and where to begin.",
    sections: [
      ["Local SEO vs. regular SEO", ["Regular SEO tries to rank a website for a search term anywhere. Local SEO is for searches with a place attached, such as \"plumber near me\" or \"accountant in Cranford.\" Google shows local results with a map and a list of businesses, often above regular website results."]],
      ["What Google looks at", ["Google has said local results are based mainly on relevance, distance and prominence. Relevance is how well your profile and site match the search. Distance is how far you are from the searcher or the place searched. Prominence is how well-known you are, which reviews, links and mentions all feed into."]],
      ["The pieces you control", ["A complete, accurate Google Business Profile. A fast, mobile-friendly website with clear service pages. Consistent business details across the web. Genuine reviews. A site that says clearly where you work."]],
      ["What you do not control", ["Where the searcher is standing, how many competitors are nearby, and how Google weighs each factor at a given moment. This is why no one can honestly promise a ranking."]],
      ["Where to start", ["Claim and complete your Business Profile, make sure your site loads fast on a phone, and write a page for each main service. Then ask happy customers for reviews. See our local SEO checklist."]],
    ],
    faqs: [["Do I need a website for local SEO?", "A Business Profile alone can bring calls, but a website gives Google and customers more to go on and is worth having."], ["Does local SEO work for service-area businesses?", "Yes. You can set the areas you serve, and service and town pages help show where you work."]] },
  { slug: "how-to-set-up-google-business-profile", title: "How to set up your Google Business Profile", updated: "2026-10-07", services: ["google-business-profile", "local-seo"],
    description: "A step-by-step guide to claiming, verifying and completing a Google Business Profile for a local business, without breaking Google's rules.",
    intro: "A complete profile is the cheapest and fastest local SEO step. Here is how to do it properly.",
    sections: [
      ["Check if one already exists", ["Search for your business name and address. Google often creates profiles on its own. If one exists, claim it instead of making a duplicate. If someone else controls it, use Google's ownership request."]],
      ["Use your real business name", ["Enter the name exactly as it appears on your sign, invoices and website. Adding keywords or a city to the name violates Google's guidelines and can get the profile suspended."]],
      ["Choose categories carefully", ["The primary category matters most. Pick the one that describes your core business, then add a few accurate secondary categories. Look at what competitors who rank well use."]],
      ["Address and service areas", ["If customers visit you, show your address. If you travel to customers, you can hide the address and list the areas you serve. Do not list a P.O. box or a virtual office as a storefront. Check Google's current rules on eligibility."]],
      ["Verify", ["Google decides the method: postcard, phone, email, text or video. Follow the steps shown and keep the profile accurate while you wait."]],
      ["Complete everything", ["Add hours, phone, website, a short honest description, services and real photos of your work and location. Keep holiday hours updated."]],
      ["Maintain it", ["Answer reviews, post updates occasionally and keep details current. An outdated profile loses trust quickly."]],
    ],
    faqs: [["How long does verification take?", "From instant to a couple of weeks, depending on the method Google offers."], ["Can I have more than one profile?", "Only for real, separate locations that meet Google's rules. Do not create duplicates."]] },
  { slug: "how-to-get-more-google-reviews", title: "How to get more Google reviews (the right way)", updated: "2026-10-07", services: ["google-business-profile", "local-seo"],
    description: "How to ask for Google reviews, what Google's policies allow, and how to respond to reviews, including the negative ones.",
    intro: "Reviews help customers decide and are part of how Google judges prominence. The way you ask matters, because some common tactics break the rules.",
    sections: [
      ["Ask at the right moment", ["Ask right after a job goes well, when the customer is happiest. Send a short, personal message with your direct review link. Do not ask everyone at once through a mass email list."]],
      ["Make it easy", ["Use the review link from your Business Profile. Put it in your invoice email, text follow-up or a QR code. The fewer steps, the more reviews."]],
      ["What not to do", ["Do not offer discounts or gifts in exchange for reviews. Do not only ask happy customers while screening out unhappy ones (review gating). Do not write reviews yourself, buy reviews or ask staff and relatives to post them. Google's policies prohibit these and can remove reviews or penalize a profile. Check the current policy."]],
      ["Respond to every review", ["Thank reviewers by name. For negative reviews, respond calmly, acknowledge the issue, offer to resolve it offline and do not argue. Prospective customers read your responses."]],
      ["Be patient", ["A steady trickle of real reviews beats a sudden spike. Make asking part of your routine."]],
    ],
    faqs: [["Can I delete a bad review?", "Only if it violates Google's policies, such as spam or fake content. You can flag it for review. Otherwise respond professionally."], ["Can I ask for reviews on other sites?", "Yes, but follow each site's rules. Google reviews matter most for local search."]] },
  { slug: "local-seo-checklist-for-small-business", title: "A local SEO checklist for small businesses", updated: "2026-10-07", services: ["local-seo", "technical-seo-and-schema"],
    description: "A practical checklist for local SEO covering your Business Profile, website, listings, reviews and tracking, in the order that gets the most from your time.",
    intro: "Work through this in order. The first few items usually matter most.",
    sections: [
      ["Google Business Profile", ["Claimed, verified and complete. Right categories. Accurate hours and phone. Real photos. No keywords added to the name."]],
      ["Website basics", ["Loads quickly on a phone. Clear page for each main service. Your address or service area, phone number and hours visible. Contact form that works. HTTPS."]],
      ["On-page details", ["A unique title and description on each page. One clear main heading. Descriptive image file names and alt text. Internal links between related pages."]],
      ["Listings and consistency", ["The same business name, address and phone number on your site, Business Profile and major directories. Fix or remove wrong or duplicate listings."]],
      ["Reviews", ["A routine for asking. Responses to every review. No fake or incentivized reviews."]],
      ["Structured data", ["Local business schema on the home page and contact page. FAQ and breadcrumb markup where it matches visible content."]],
      ["Tracking", ["Search Console verified, sitemap submitted, analytics installed, and calls and form submissions tracked."]],
      ["Review monthly", ["Check Search Console for errors, look at which searches bring visitors and update pages when your business changes."]],
    ],
    faqs: [["Which item should I do first?", "The Google Business Profile. It is free and often gives the quickest return."], ["Can I do this myself?", "Yes, most of it. We help when you want it done faster or checked."]] },
  { slug: "nap-consistency-and-local-citations", title: "NAP consistency and local citations: do they still matter?", updated: "2026-10-07", services: ["google-business-profile", "local-seo"],
    description: "What NAP and citations are, why consistent business details matter, and a sensible approach that avoids paying for dozens of directory listings.",
    intro: "NAP stands for name, address and phone number. Keeping them consistent helps Google and customers trust that your business is real and current.",
    sections: [
      ["What a citation is", ["A citation is any mention of your business details online, such as a directory listing, a chamber of commerce page or a social profile. Links are a bonus, but the details themselves count."]],
      ["Why consistency matters", ["Conflicting phone numbers or addresses confuse customers and can confuse Google. They also cause duplicate listings and wrong information in maps and apps."]],
      ["A sensible approach", ["Decide your exact business name, address format and primary phone number. Match them on your site, Business Profile and the major platforms that matter for your trade. Fix errors you find. You do not need hundreds of listings."]],
      ["Watch for old information", ["Moved, changed phone numbers or rebranded? Search for the old details and update or remove those listings."]],
      ["Skip the spam directories", ["Paying for mass directory submissions rarely helps and can create clutter. Focus on a small set of accurate, relevant listings."]],
    ],
    faqs: [["Do I need to pay for a listing service?", "Usually not. Most important listings are free to claim and update."], ["What if I use a call-tracking number?", "Use a tracking number carefully and keep your main number listed consistently. Check Google's guidance."]] },
  { slug: "how-to-write-service-pages-that-help", title: "How to write service and town pages that actually help", updated: "2026-10-07", services: ["local-seo", "website-design"],
    description: "How to write a page for each service and each area you serve without creating thin duplicate pages that Google may ignore.",
    intro: "Pages for each service and area can bring in local searches. Done lazily, they become copies with the town name swapped, which helps no one.",
    sections: [
      ["One page per real service", ["Give each main service its own page: what it is, who needs it, how it works, what it costs or how pricing works, and how to book. Answer the questions customers really ask."]],
      ["Town pages only where you work", ["A page for a town makes sense if you really serve it. Include local detail: places you work near, kinds of customers there, local rules or logistics, and nearby towns."]],
      ["Avoid thin, repeated pages", ["Pages that differ only by the town name are doorway pages. Google's guidelines warn against them. If you cannot say anything real about a town, do not make a page for it."]],
      ["Structure", ["A clear title and heading with the service and place. Short sections. A phone number and a way to book. FAQ answering real questions. Links to related services and nearby areas."]],
      ["Keep facts true", ["Do not invent testimonials, statistics or client names. Say what you actually do."]],
    ],
    faqs: [["How many town pages should I have?", "As many as you can write something useful for. A few good pages beat dozens of copies."], ["Should the pages link to each other?", "Yes. Link related services and nearby towns so visitors and Google can find them."]] },
  { slug: "title-tags-and-meta-descriptions", title: "Title tags and meta descriptions: how to write them", updated: "2026-10-07", services: ["technical-seo-and-schema", "local-seo"],
    description: "How to write page titles and meta descriptions that match search intent and earn clicks, with examples for a local service business.",
    intro: "The title and description are what people see in search results. They do not guarantee a ranking, but they help people choose your page.",
    sections: [
      ["Title tags", ["Write a unique title for each page that says what the page is and where you serve, with your business name at the end. Keep it short enough to display, roughly 50 to 60 characters, though Google may rewrite titles."]],
      ["Meta descriptions", ["The description does not directly affect rankings, but Google often shows it. Write one or two sentences that describe the page honestly and give a reason to click, such as pricing, speed or service area. Google may substitute its own text."]],
      ["Avoid", ["The same title on every page. Stuffing in keywords. Writing for search engines instead of people. Promises the page does not keep."]],
      ["An example", ["For a mobile notary: \"Mobile Notary in Cranford, NJ | Same-Day Visits | MCC Solutions\" with a description that says what is offered, where and how to book."]],
      ["Check in Search Console", ["See which queries show your pages and which pages get clicks. Rewrite titles on pages that show often but rarely get clicked."]],
    ],
    faqs: [["Does Google use meta keywords?", "No. Google has said it ignores the meta keywords tag."], ["Why does Google show a different title?", "Google may rewrite titles it finds unhelpful or repetitive. Clear, specific titles are rewritten less."]] },
  { slug: "core-web-vitals-explained", title: "Core Web Vitals explained for small business owners", updated: "2026-10-07", services: ["website-speed"],
    description: "What LCP, INP and CLS mean, how to check them, and the common fixes that make a small business website faster on phones.",
    intro: "Core Web Vitals are Google's measures of how fast a page loads, how quickly it responds and how stable it is. Here is what they mean in practice.",
    sections: [
      ["The three measures", ["Largest Contentful Paint (LCP) is how long the main content takes to appear. Google considers 2.5 seconds or less good. Interaction to Next Paint (INP) is how quickly the page responds when someone taps; 200 milliseconds or less is considered good. Cumulative Layout Shift (CLS) is how much things jump around while loading; 0.1 or less is good. Check Google's current thresholds."]],
      ["How to check", ["Run your page through PageSpeed Insights. It shows lab tests and, when enough data exists, real-user data. The Core Web Vitals report in Search Console groups your pages."]],
      ["Common causes of slow pages", ["Oversized images. Fonts and CSS that block rendering. Too many scripts from plug-ins, chat widgets and trackers. Slow hosting without caching or compression."]],
      ["Common fixes", ["Compress and resize images, using modern formats. Load fonts efficiently. Defer scripts you do not need immediately. Turn on caching and compression. Set image sizes so the page does not jump."]],
      ["Keep it in perspective", ["Speed matters mostly because visitors leave slow sites. A good score will not outrank better content, but a bad one can cost you customers."]],
    ],
    faqs: [["Do I need a perfect score?", "No. Aim for a fast real-world experience on a phone."], ["Why does my score change each time?", "Lab tests vary with network and server conditions. Look at trends and real-user data."]] },
  { slug: "how-to-set-up-google-search-console", title: "How to set up Google Search Console for your site", updated: "2026-10-07", services: ["technical-seo-and-schema", "local-seo"],
    description: "A step-by-step guide to verifying your site in Google Search Console, submitting a sitemap, requesting indexing and reading the main reports.",
    intro: "Search Console is Google's free tool that shows how your site appears in search. Every business site should have it.",
    sections: [
      ["Add your property", ["Sign in with a Google account you control, choose a property type and add your site. A domain property covers all versions of your address. A URL-prefix property covers one."]],
      ["Verify ownership", ["Google asks you to prove you own the site, usually with a DNS record or an HTML file or tag. Keep the verification in place permanently."]],
      ["Submit your sitemap", ["Open the Sitemaps report and enter your sitemap address, usually ending in /sitemap.xml. This helps Google find your pages."]],
      ["Request indexing for key pages", ["Use URL Inspection on important pages and request indexing, especially new or updated ones. It does not guarantee indexing or a ranking."]],
      ["Read the main reports", ["Performance shows queries, clicks and impressions. Pages shows which pages are indexed and why others are not. Core Web Vitals and Mobile usability flag problems."]],
      ["Give access to your helper", ["Add your web or SEO person as a user instead of sharing your login."]],
    ],
    faqs: [["How soon will data appear?", "Usually within a few days after verification."], ["Why is a page \"discovered, not indexed\"?", "Google found it but has not crawled or chosen to index it. Improving content quality and internal links helps."]] },
  { slug: "schema-markup-for-local-business", title: "Schema markup for local businesses: what to add", updated: "2026-10-07", services: ["technical-seo-and-schema"],
    description: "What schema markup is, which types matter for a local business, and how to test it so it helps instead of hurts.",
    intro: "Schema markup is code that labels the facts on your page so search engines can read them reliably.",
    sections: [
      ["What it does", ["It does not boost rankings by itself. It helps Google understand your business and can make pages eligible for rich results such as FAQs, breadcrumbs or job listings."]],
      ["Types worth using", ["LocalBusiness (or a more specific type) on your home or contact page with name, address, phone, hours and service area. Service on service pages. FAQPage where a page has real questions and answers. BreadcrumbList for navigation. JobPosting if you hire."]],
      ["The rules", ["Markup must match what visitors can see on the page. Do not mark up reviews you do not display or invent ratings. Misleading markup can lead to a manual action."]],
      ["Test it", ["Use Google's Rich Results Test and the Search Console enhancements reports to confirm the markup is valid and eligible."]],
      ["Keep it current", ["When your hours, phone or services change, update the markup along with the page."]],
    ],
    faqs: [["Can I add schema with a plug-in?", "Yes, many plug-ins do. Check the output, because defaults are often wrong or incomplete."], ["Will FAQ schema show in results?", "Google limits when it shows FAQ results. Use it where it helps readers, not to chase a display."]] },
  { slug: "how-long-does-seo-take", title: "How long does SEO take to work?", updated: "2026-10-07", services: ["local-seo"],
    description: "An honest answer to how long local SEO takes, what changes quickly, what takes months, and what to watch to know it is working.",
    intro: "Anyone who gives you an exact date is guessing. Here is what usually moves first and what takes longer.",
    sections: [
      ["Faster changes", ["Fixing a wrong phone number, completing a Business Profile or fixing a broken page can show effects within days to weeks."]],
      ["Slower changes", ["New content has to be crawled, indexed and judged. Competitive searches with strong established rivals can take months. Reviews and reputation build over time."]],
      ["What affects the timeline", ["Your starting point, how competitive your area and trade are, the age of your site, and how consistently you keep working on it."]],
      ["How to tell it is working", ["Watch impressions and clicks in Search Console, calls from your Business Profile, form submissions and the pages that bring visitors. Compare month to month, not day to day."]],
      ["Be wary of guarantees", ["Promises of first-page results in 30 days are a red flag. Google decides rankings, and no outside party controls them."]],
    ],
    faqs: [["Is SEO a one-time job?", "Foundations can be done once. Results hold up better when you keep content, reviews and details current."], ["Can ads fill the gap?", "Paid ads can bring traffic faster, at a cost per click. SEO builds over time without a per-click fee."]] },
  { slug: "how-to-choose-an-seo-company", title: "How to choose an SEO company (and the red flags)", updated: "2026-10-07", services: ["local-seo"],
    description: "What to ask an SEO or web agency before you hire, the promises that should make you walk away, and how to make sure you keep ownership of your accounts.",
    intro: "Small business owners get a lot of cold emails promising page one. Here is how to tell honest help from a pitch.",
    sections: [
      ["Questions to ask", ["What exactly will you do each month? Who does the work? Which accounts will be in my name? How will you report results? Can I talk to current customers?"]],
      ["Red flags", ["Guaranteed rankings. Secret methods. Very cheap monthly packages that promise hundreds of links. Wanting to own your domain, Business Profile or analytics. Refusing to explain what they changed. Cold emails saying your site has errors, with no specifics."]],
      ["Ownership", ["You should own your domain, hosting, Business Profile, Search Console and analytics. Add the agency as a user. If they leave, you keep everything."]],
      ["Reporting", ["Good reports are plain and show real data: Search Console queries, calls, leads and what was done. Vanity numbers without context are a warning."]],
      ["Contracts", ["Prefer short or month-to-month terms and a clear scope. Understand what happens if you stop."]],
    ],
    faqs: [["Is cheap SEO bad?", "Not always, but very cheap packages often mean automated or low-quality work. Ask what you get."], ["Should I hire locally?", "It can help for communication, but quality and honesty matter more than location."]] },
  { slug: "how-much-does-a-small-business-website-cost", title: "How much does a small business website cost?", updated: "2026-10-07", services: ["website-design", "website-care"],
    description: "What drives the cost of a small business website, the difference between a template and a custom build, and the ongoing costs people forget.",
    intro: "There is no standard price, and a fair quote depends on what the site must do. Here is what moves the number.",
    sections: [
      ["What drives the price", ["The number of pages. Whether you need booking, payments or a client login. How much content and photography is ready. Whether the design is custom or based on a template. The amount of SEO and tracking set up at launch."]],
      ["Template vs. custom", ["Templates and website builders cost less up front and suit simple businesses. Custom builds cost more and suit businesses with specific needs, performance requirements or growth plans."]],
      ["Ongoing costs", ["Domain renewal, hosting, software or plug-in licenses, and updates or care. Ask for these in writing, including what renews automatically."]],
      ["Ask for a fixed written quote", ["A clear scope, price and timeline protects both sides. Be careful with vague hourly estimates and with agencies that will not say what is included."]],
      ["Ownership", ["You should own the domain, hosting accounts and content. See our guide on domain and hosting ownership."]],
    ],
    faqs: [["Can I just use a site builder?", "For simple businesses, yes. Weigh time, design, speed, SEO limits and who maintains it."], ["Why do quotes differ so much?", "Scope, quality and who does the work. Compare what is included, not only the price."]] },
  { slug: "what-every-local-business-website-needs", title: "What every local business website needs", updated: "2026-10-07", services: ["website-design", "website-speed"],
    description: "The essential pages and details a local business website needs to turn visitors into calls, including mobile, speed, trust and clear contact information.",
    intro: "Most local customers decide in seconds. These are the things a site needs so they can.",
    sections: [
      ["Say what you do and where", ["The home page should say, in plain words, what you do and where you serve. Do this above the fold on a phone."]],
      ["Contact information everywhere", ["A tappable phone number, hours, address or service area, and a contact form. Make the next step obvious."]],
      ["Service pages", ["One page per main service with details, how it works, how pricing works and how to book."]],
      ["Trust", ["Real photos, your credentials and licenses, honest descriptions and actual customer reviews. Do not invent testimonials or logos."]],
      ["Mobile and speed", ["Most visitors use a phone. The site must load fast, be readable and work with a thumb. See our Core Web Vitals guide."]],
      ["The basics Google likes", ["HTTPS, clear titles and headings, a sitemap, and structured data that matches the page."]],
      ["Accessibility", ["Readable text, enough contrast, labeled forms and alt text on images. It helps everyone and reduces legal risk."]],
    ],
    faqs: [["Do I need a blog?", "Not necessarily. A few helpful guides on real customer questions are enough."], ["Do I need online booking?", "Only if it helps customers. A clear form or phone number often does the job."]] },
  { slug: "own-your-domain-and-hosting", title: "Who owns your domain and hosting? Check now", updated: "2026-10-07", services: ["website-design", "website-care"],
    description: "How to check who owns your domain, hosting and Google accounts, why it matters when you change web providers, and how to take control.",
    intro: "Many owners find out too late that their web developer registered the domain in the developer's name. A five-minute check prevents that.",
    sections: [
      ["Domain registration", ["Your domain should be registered to you or your business, with your email on the account. Look up your domain on a WHOIS service or log in to the registrar. If you cannot, ask your provider for access."]],
      ["Hosting and website admin", ["You should have admin logins for your hosting account and website. If the site runs on a platform, you should be the account owner."]],
      ["Google accounts", ["Your Business Profile, Search Console and analytics should be owned by an account you control, with your provider added as a user."]],
      ["How to take control", ["Ask for transfer or admin access in writing. Domain transfers use an authorization code and normally take a few days. Keep renewal reminders on a calendar."]],
      ["Protect yourself", ["Use a business email you control for all accounts. Turn on two-step sign-in. Store logins in a password manager."]],
    ],
    faqs: [["What if my developer will not hand over the domain?", "Ask in writing first. If the domain is in their name, a registrar dispute process or an attorney may be needed. Prevention is much easier."], ["Do I need to renew the domain every year?", "Registrations expire. Turn on auto-renew and keep a valid payment card and email on file."]] },
];

module.exports = { SERVICES, GUIDES };
